package flaotec.KFZ_Kennzeichen;

import java.util.ArrayList;

import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.text.SpannableString;
import android.text.style.StyleSpan;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.TableLayout;
import android.widget.TableRow;
import android.widget.TextView;

public class KFZdatabase {
	private String[] aSuch = { 
			"F","01","Ain(Bourg-en-Bresse)","Rhône-Alpes","",
			"F","02","Aisne(Laon)","Picardie","",
			"F","03","Allier(Moulins)","Auvergne","",
			"F","04","Alpes-de-Haute-Provence(Digne-les-Bains)","Provence-Alpes-Côte d’Azur","",
			"F","05","Hautes-Alpes(Gap)","Provence-Alpes-Côte d’Azur","",
			"F","06","Alpes-Maritimes(Nizza)","Provence-Alpes-Côte d’Azur","",
			"F","07","Ardèche(Privas)","Rhône-Alpes","",
			"F","08","Ardennes(Charleville-Mézières)","Champagne-Ardenne","",
			"F","09","Ariège(Foix)","Midi-Pyrénées","",
			"F","10","Aube(Troyes)","Champagne-Ardenne","",
			"F","11","Aude(Carcassonne)","Languedoc-Roussillon","",
			"F","12","Aveyron(Rodez)","Midi-Pyrénées","",
			"F","13","Bouches-du-Rhône(Marseille)","Provence-Alpes-Côte d’Azur","",
			"F","14","Calvados(Caen)","Basse-Normandie","",
			"F","15","Cantal(Aurillac)","Auvergne","",
			"F","16","Charente(Angoulême)","Poitou-Charentes","",
			"F","17","Charente-Maritime(La Rochelle)","Poitou-Charentes","",
			"F","18","Cher(Bourges)","Centre","",
			"F","19","Corrèze(Tulle)","Limousin","",
			"F","2A","Corse-du-Sud(Ajaccio)","Corse (Korsika)","",
			"F","2B","Haute-Corse(Bastia)","Corse (Korsika)","",
			"F","21","Côte-d’Or(Dijon)","Bourgogne (Burgund)","",
			"F","22","Côtes-d’Armor(Saint-Brieuc)","Bretagne","",
			"F","23","Creuse(Guéret)","Limousin","",
			"F","24","Dordogne(Périgueux)","Aquitaine (Aquitanien)","",
			"F","25","Doubs(Besançon)","Franche-Comté","",
			"F","26","Drôme(Valence)","Rhône-Alpes","",
			"F","27","Eure(Évreux)","Haute-Normandie","",
			"F","28","Eure-et-Loir(Chartres)","Centre","",
			"F","29","Finistère(Quimper)","Bretagne","",
			"F","30","Gard(Nîmes)","Languedoc-Roussillon","",
			"F","31","Haute-Garonne(Toulouse)","Midi-Pyrénées","",
			"F","32","Gers(Auch)","Midi-Pyrénées","",
			"F","33","Gironde(Bordeaux)","Aquitaine (Aquitanien)","",
			"F","34","Hérault(Montpellier)","Languedoc-Roussillon","",
			"F","35","Ille-et-Vilaine(Rennes)","Bretagne","",
			"F","36","Indre(Châteauroux)","Centre","",
			"F","37","Indre-et-Loire(Tours)","Centre","",
			"F","38","Isère(Grenoble)","Rhône-Alpes","",
			"F","39","Jura(Lons-le-Saunier)","Franche-Comté","",
			"F","40","Landes(Mont-de-Marsan)","Aquitaine (Aquitanien)","",
			"F","41","Loir-et-Cher(Blois)","Centre","",
			"F","42","Loire(Saint-Étienne)","Rhône-Alpes","",
			"F","43","Haute-Loire(Le Puy-en-Velay)","Auvergne","",
			"F","44","Loire-Atlantique(Nantes)","Pays de la Loire","",
			"F","45","Loiret(Orléans)","Centre","",
			"F","46","Lot(Cahors)","Midi-Pyrénées","",
			"F","47","Lot-et-Garonne(Agen)","Aquitaine (Aquitanien)","",
			"F","48","Lozère(Mende)","Languedoc-Roussillon","",
			"F","49","Maine-et-Loire(Angers)","Pays de la Loire","",
			"F","50","Manche(Saint-Lô)","Basse-Normandie","",
			"F","51","Marne(Châlons-en-Champagne)","Champagne-Ardenne","",
			"F","52","Haute-Marne(Chaumont)","Champagne-Ardenne","",
			"F","53","Mayenne(Laval)","Pays de la Loire","",
			"F","54","Meurthe-et-Moselle(Nancy)","Lorraine (Lothringen)","",
			"F","55","Meuse(Bar-le-Duc)","Lorraine (Lothringen)","",
			"F","56","Morbihan(Vannes)","Bretagne","",
			"F","57","Moselle(Metz)","Lorraine (Lothringen)","",
			"F","58","Nièvre(Nevers)","Bourgogne (Burgund)","",
			"F","59","Nord(Lille)","Nord-Pas-de-Calais","",
			"F","60","Oise(Beauvais)","Picardie","",
			"F","61","Orne(Alençon)","Basse-Normandie","",
			"F","62","Pas-de-Calais(Arras)","Nord-Pas-de-Calais","",
			"F","63","Puy-de-Dôme(Clermont-Ferrand)","Auvergne","",
			"F","64","Pyrénées-Atlantiques(Pau)","Aquitaine (Aquitanien)","",
			"F","65","Hautes-Pyrénées(Tarbes)","Midi-Pyrénées","",
			"F","66","Pyrénées-Orientales(Perpignan)","Languedoc-Roussillon","",
			"F","67","Bas-Rhin(Straßburg)","Alsace (Elsass)","",
			"F","68","Haut-Rhin(Colmar)","Alsace (Elsass)","",
			"F","69","Rhône(Lyon)","Rhône-Alpes","",
			"F","70","Haute-Saône(Vesoul)","Franche-Comté","",
			"F","71","Saône-et-Loire(Mâcon)","Bourgogne (Burgund)","",
			"F","72","Sarthe(Le Mans)","Pays de la Loire","",
			"F","73","Savoie(Chambéry)","Rhône-Alpes","",
			"F","74","Haute-Savoie(Annecy)","Rhône-Alpes","",
			"F","75","Paris(Paris)","Île-de-France","",
			"F","76","Seine-Maritime(Rouen)","Haute-Normandie","",
			"F","77","Seine-et-Marne(Melun)","Île-de-France","",
			"F","78","Yvelines(Versailles)","Île-de-France","",
			"F","79","Deux-Sèvres(Niort)","Poitou-Charentes","",
			"F","80","Somme(Amiens)","Picardie","",
			"F","81","Tarn(Albi)","Midi-Pyrénées","",
			"F","82","Tarn-et-Garonne(Montauban)","Midi-Pyrénées","",
			"F","83","Var(Toulon)","Provence-Alpes-Côte d’Azur","",
			"F","84","Vaucluse(Avignon)","Provence-Alpes-Côte d’Azur","",
			"F","85","Vendée(La Roche-sur-Yon)","Pays de la Loire","",
			"F","86","Vienne(Poitiers)","Poitou-Charentes","",
			"F","87","Haute-Vienne(Limoges)","Limousin","",
			"F","88","Vosges(Épinal)","Lorraine (Lothringen)","",
			"F","89","Yonne(Auxerre)","Bourgogne (Burgund)","",
			"F","90","Territoire de Belfort(Belfort)","Franche-Comté","",
			"F","91","Essonne(Évry)","Île-de-France","",
			"F","92","Hauts-de-Seine(Nanterre)","Île-de-France","",
			"F","93","Seine-Saint-Denis(Bobigny)","Île-de-France","",
			"F","94","Val-de-Marne(Créteil)","Île-de-France","",
			"F","95","Val-d’Oise(Pontoise)","Île-de-France","",
			"F","971","Guadeloupe(Basse-Terre)","Guadeloupe","",
			"F","972","Martinique(Fort-de-France)","Martinique","",
			"F","973","Guyane(Cayenne)","Guyane (Französisch-Guayana)","",
			"F","974","Réunion(Saint-Denis)","Réunion","",
			"F","976","Mayotte(Mamoudzou)","Mayotte","",
			"AT", "A", "Oberste Organe Österreich", "Österreich", "",
			"AT", "AM", "Amstetten", "Niederösterreich", "",
			"AT", "B", "Bregenz", "Vorarlberg", "", 
			"AT", "BA", "Bad Aussee", "Steiermark", "",
			"AT", "BB", "Österreichische Bundesbahnen", "Österreich", "",
			"AT", "BH", "Bundesheer", "Österreich", "",
			"AT", "BL", "Bruck an der Leitha", "Niederösterreich", "", 
			"AT", "BM", "Bruck an der Mur", "Steiermark", "",
			"AT", "BN", "Baden", "Niederösterreich", "",
			"AT", "BP", "Bundespolizei Österreich", "Österreich", "",
			"AT", "BR", "Branau am Inn", "Oberösterreich", "", 
			"AT", "BZ", "Bludenz", "Vorarlberg", "", 
			"AT", "DL", "Deutschlandsberg", "Steiermark", "", 
			"AT", "DO", "Dornbirn", "Vorarlberg", "", 
			"AT", "E", "Eisenstadt Stadt", "Burgenland", "", 
			"AT", "EF", "Eferding", "Oberösterreich", "", 
			"AT", "EU", "Eisenstadt Umgebung", "Burgenland", "", 
			"AT", "FB", "Feldbach", "Steiermark","", 
			"AT", "FE", "Feldkirchen", "Kärnten", "", 
			"AT", "FF", "Fürstenfeld","Steiermark", "", 
			"AT", "FK", "Feldkirch", "Vorarlberg", "", 
			"AT", "FR", "Freistadt","Oberösterreich", "",
			"AT", "FV", "Finanzverwaltung", "Österreich", "",
			"AT", "G", "Graz Stadt", "Steiermark", "", 
			"AT", "GB", "Gröbming", "Steiermark", "",
			"AT", "GD", "Gmünd", "Niederösterreich", "", 
			"AT", "GF", "Gänserndorf", "Niederösterreich", "",
			"AT", "GM", "Gmunden", "Oberösterreich", "", 
			"AT", "GR", "Grieskirchen", "Oberösterreich", "",
			"AT", "GS", "Güssing", "Burgenland", "", 
			"AT", "GU", "Graz Umgebung", "Steiermark", "",
			"AT", "HA", "Hallein", "Salzburg", "", 
			"AT", "HB", "Hartberg", "Steiermark", "",
			"AT", "HE", "Hermagor", "Kärnten", "", 
			"AT", "HL", "Hollabrunn", "Niederösterreich", "",
			"AT", "HO", "Horn", "Niederösterreich", "", 
			"AT", "I", "Innsbruck Stadt", "Tirol", "",
			"AT", "IL", "Innsbruck Land", "Tirol", "", 
			"AT", "IM", "Imst", "Tirol", "",
			"AT", "JE", "Jennersdorf", "Burgenland", "", 
			"AT", "JO", "St. Johann im Pongau", "Salzburg","",
			"AT", "JW", "Justizwache Österreich", "Österreich", "", 
			"AT", "JU", "Judenburg", "Steiermark", "", 
			"AT", "K", "Klagenfurt Stadt", "Kärnten","", 
			"AT", "KB", "Kitzbühel", "Tirol", "", 
			"AT", "KF", "Knittelfeld", "Steiermark","", 
			"AT", "KI", "Kirchdorf an der Krems", "Oberösterreich", "", 
			"AT", "KL", "Klagenfurt Umgebung", "Kärnten", "", 
			"AT", "KO", "Korneuburg", "Niederösterreich", "", 
			"AT", "KR", "Krems an der Donau Land", "Niederösterreich", "", 
			"AT", "KS", "Krems an der Donau", "Niederösterreich","", 
			"AT", "KU", "Kufstein", "Tirol", "", 
			"AT", "L", "Linz Stadt", "Oberösterreich", "",
			"AT", "LA", "Landeck", "Tirol", "", 
			"AT", "LB", "Leibnitz", "Steiermark", "",
			"AT", "LE", "Leoben", "Steiermark", "", 
			"AT", "LF", "Lilienfeld", "Niederösterreich","", 
			"AT", "LI", "Liezen", "", "", 
			"AT", "LL", "Linz Umgebung", "Oberösterreich", "",
			"AT", "LN", "Leoben Land", "Steiermark", "", 
			"AT", "LZ", "Lienz", "Tirol", "",
			"AT", "MA", "Mattersburg", "Burgenland", "", 
			"AT", "MD", "Mödling", "Niederösterreich", "",
			"AT", "ME", "Melk", "Niederösterreich", "", 
			"AT", "MI", "Mistelbach", "Niederösterreich", "", 
			"AT", "MU", "Murau", "Steiermark", "", 
			"AT", "MZ", "Mürzzuschlag", "Steiermark", "", 
			"AT", "ND", "Neusiedl am See", "Burgenland", "", 
			"AT", "NK", "Neunkirchen", "Niederösterreich", "",
			"AT", "OP", "Oberpullendorf", "Burgenland", "", 
			"AT", "OW", "Oberwart", "Burgenland", "",
			"AT", "P", "St. Pölten Stadt", "Niederösterreich", "", 
			"AT", "PE", "Perg", "Oberösterreich", "",
			"AT", "PL", "St. Pölten Umgebung", "Niederösterreich", "",
			"AT", "PT", "Östereichische Post", "Österreich", "",
			"AT", "RA", "Bad Radkersburg", "Steiermark","", 
			"AT", "RE", "Reutte", "Tirol", "", 
			"AT", "RI", "Ried am Innkreis","Oberösterreich", "", 
			"AT", "RO", "Rohrbach im Mühlkreis", "Oberösterreich", "", 
			"AT", "S", "Salzburg Stadt", "Salzburg", "", 
			"AT", "SB", "Scheibbs", "Niederösterreich", "", 
			"AT", "SD", "Schärding", "Oberösterreich", "", 
			"AT", "SE", "Steyr Land", "Oberösterreich", "", 
			"AT", "SL", "Salzburg Umgebung", "Salzburg", "", 
			"AT", "SP", "Spittal an der Drau", "Kärnten","", 
			"AT", "SR", "Steyr", "Oberösterreich", "", 
			"AT", "SV", "St. Veit an der Glan", "Kärnten", "", 
			"AT", "SW", "Schwechat", "Niederösterreich", "", 
			"AT", "SZ", "Schwaz", "Tirol", "", 
			"AT", "TA", "Tamsweg", "Salzburg", "", 
			"AT", "TU", "Tulln", "Niederösterreich", "", 
			"AT", "UU", "Urfahr Land", "Oberösterreich", "", 
			"AT", "VB", "Vöcklabruck", "Oberösterreich", "", 
			"AT", "VI", "Villach Stadt", "Kärnten", "", 
			"AT", "VK", "Völkermarkt", "Kärnten", "", 
			"AT", "VL", "Villach Land", "Kärnten", "",
			"AT", "VO", "Voitsberg", "Steiermark", "", 
			"AT", "W", "Wien", "Wien", "",
			"AT", "WB", "Wiener Neustadt Land", "Niederösterreich", "",
			"AT", "WD", "Korps Wien", "Österreich", "", 
			"AT", "WE", "Wels Stadt", "Oberösterreich", "", 
			"AT", "WL", "Wels Land", "Oberösterreich", "", 
			"AT", "WN", "Wiener Neustadt", "Niederösterreich", "", 
			"AT", "WO", "Wolfsberg", "Kärnten", "",
			"AT", "WT", "Waidhofen an der Thaya", "Niederösterreich", "", 
			"AT", "WU", "Wien Umgebung", "Niederösterreich", "", 
			"AT", "WY", "Waidhofen an der Ybbs", "Niederösterreich", "",
			"AT", "WZ", "Weiz", "Steiermark", "", 
			"AT", "ZE", "Zell am See", "Salzburg", "",
			"AT", "ZT", "Zwettl", "Niederösterreich", "",  "CH", "AG", "Kanton Aargau", "", "",
			
			"Land","Kürzel","Bezeichnung","Region","",
			"PL","DB","Powiat Wałbrzyski, früher Wałbrzych","Dolnośląskie (Niederschlesien)","",
			"PL","DBA","früher Powiat Wałbrzyski → DB","Dolnośląskie (Niederschlesien)","",
			"PL","DBL","Powiat Bolesławiecki","Dolnośląskie (Niederschlesien)","",
			"PL","DDZ","Powiat Dzierżoniowski","Dolnośląskie (Niederschlesien)","",
			"PL","DGL","Powiat Głogowski","Dolnośląskie (Niederschlesien)","",
			"PL","DGR","Powiat Górowski","Dolnośląskie (Niederschlesien)","",
			"PL","DJ","Jelenia Góra","Dolnośląskie (Niederschlesien)","",
			"PL","DJA","Powiat Jaworski","Dolnośląskie (Niederschlesien)","",
			"PL","DJE","Powiat Jeleniogórski","Dolnośląskie (Niederschlesien)","",
			"PL","DKA","Powiat Kamiennogórski","Dolnośląskie (Niederschlesien)","",
			"PL","DKL","Powiat Kłodzki","Dolnośląskie (Niederschlesien)","",
			"PL","DL","Legnica","Dolnośląskie (Niederschlesien)","",
			"PL","DLB","Powiat Lubański","Dolnośląskie (Niederschlesien)","",
			"PL","DLE","Powiat Legnicki","Dolnośląskie (Niederschlesien)","",
			"PL","DLU","Powiat Lubiński","Dolnośląskie (Niederschlesien)","",
			"PL","DLW","Powiat Lwówecki","Dolnośląskie (Niederschlesien)","",
			"PL","DMI","Powiat Milicki","Dolnośląskie (Niederschlesien)","",
			"PL","DOA","Powiat Oławski","Dolnośląskie (Niederschlesien)","",
			"PL","DOL","Powiat Oleśnicki","Dolnośląskie (Niederschlesien)","",
			"PL","DPL","Powiat Polkowicki","Dolnośląskie (Niederschlesien)","",
			"PL","DSR","Powiat Średzki","Dolnośląskie (Niederschlesien)","",
			"PL","DST","Powiat Strzeliński","Dolnośląskie (Niederschlesien)","",
			"PL","DSW","Powiat Świdnicki","Dolnośląskie (Niederschlesien)","",
			"PL","DTR","Powiat Trzebnicki","Dolnośląskie (Niederschlesien)","",
			"PL","DW","Wrocław","Dolnośląskie (Niederschlesien)","",
			"PL","DWL","Powiat Wołowski","Dolnośląskie (Niederschlesien)","",
			"PL","DWR","Powiat Wrocławski","Dolnośląskie (Niederschlesien)","",
			"PL","DZA","Powiat Ząbkowicki","Dolnośląskie (Niederschlesien)","",
			"PL","DZG","Powiat Zgorzelecki","Dolnośląskie (Niederschlesien)","",
			"PL","DZL","Powiat Złotoryjski","Dolnośląskie (Niederschlesien)","",
			"PL","CAL","Powiat Aleksandrowski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CB","Bydgoszcz","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CBR","Powiat Brodnicki","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CBY","Powiat Bydgoski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CCH","Powiat Chełmiński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CG","Grudziądz","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CGD","Powiat Golubsko-Dobrzyński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CGR","Powiat Grudziądzki","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CIN","Powiat Inowrocławski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CLI","Powiat Lipnowski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CMG","Powiat Mogileński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CNA","Powiat Nakielski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CRA","Powiat Radziejowski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CRY","Powiat Rypiński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CSE","Powiat Sępoleński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CSW","Powiat Świecki","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CT","Toruń","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CTR","Powiat Toruński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CTU","Powiat Tucholski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CW","Włocławek","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CWA","Powiat Wąbrzeski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CWL","Powiat Włocławski","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","CZN","Powiat Żniński","Kujawsko-Pomorskie (Kujawien-Pommern)","",
			"PL","EBE","Powiat Bełchatowski","Łódzkie (Lodz)","",
			"PL","EBR","Powiat Brzeziński","Łódzkie (Lodz)","",
			"PL","EKU","Powiat Kutnowski","Łódzkie (Lodz)","",
			"PL","EL","Łódź","Łódzkie (Lodz)","",
			"PL","ELA","Powiat Łaski","Łódzkie (Lodz)","",
			"PL","ELC","Powiat Łowicki","Łódzkie (Lodz)","",
			"PL","ELE","Powiat Łęczycki","Łódzkie (Lodz)","",
			"PL","ELW","Powiat Łódzki wschodni","Łódzkie (Lodz)","",
			"PL","EOP","Powiat Opoczyński","Łódzkie (Lodz)","",
			"PL","EP","Piotrków Trybunalski","Łódzkie (Lodz)","",
			"PL","EPA","Powiat Pabianicki","Łódzkie (Lodz)","",
			"PL","EPD","Powiat Poddębicki","Łódzkie (Lodz)","",
			"PL","EPI","Powiat Piotrkowski","Łódzkie (Lodz)","",
			"PL","EPJ","Powiat Pajęczański","Łódzkie (Lodz)","",
			"PL","ERA","Powiat Radomszczański","Łódzkie (Lodz)","",
			"PL","ERW","Powiat Rawski","Łódzkie (Lodz)","",
			"PL","ES","Skierniewice","Łódzkie (Lodz)","",
			"PL","ESI","Powiat Sieradzki","Łódzkie (Lodz)","",
			"PL","ESK","Powiat Skierniewicki","Łódzkie (Lodz)","",
			"PL","ETM","Powiat Tomaszowski","Łódzkie (Lodz)","",
			"PL","EWE","Powiat Wieruszowski","Łódzkie (Lodz)","",
			"PL","EWI","Powiat Wieluński","Łódzkie (Lodz)","",
			"PL","EZD","Powiat Zduńskowolski","Łódzkie (Lodz)","",
			"PL","EZG","Powiat Zgierski","Łódzkie (Lodz)","",
			"PL","LB","Biała Podlaska","Lubelskie (Lublin)","",
			"PL","LBI","Powiat Bialski","Lubelskie (Lublin)","",
			"PL","LBL","Powiat Biłgorajski","Lubelskie (Lublin)","",
			"PL","LC","Chełm","Lubelskie (Lublin)","",
			"PL","LCH","Powiat Chełmski","Lubelskie (Lublin)","",
			"PL","LHR","Powiat Hrubieszowski","Lubelskie (Lublin)","",
			"PL","LJA","Powiat Janowski","Lubelskie (Lublin)","",
			"PL","LKR","Powiat Kraśnicki","Lubelskie (Lublin)","",
			"PL","LKS","Powiat Krasnostawski","Lubelskie (Lublin)","",
			"PL","LLB","Powiat Lubartowski","Lubelskie (Lublin)","",
			"PL","LLE","Powiat Łęczyński","Lubelskie (Lublin)","",
			"PL","LLU","Powiat Łukowski","Lubelskie (Lublin)","",
			"PL","LOP","Powiat Opolski","Lubelskie (Lublin)","",
			"PL","LPA","Powiat Parczewski","Lubelskie (Lublin)","",
			"PL","LPU","Powiat Puławski","Lubelskie (Lublin)","",
			"PL","LRA","Powiat Radzyński","Lubelskie (Lublin)","",
			"PL","LRY","Powiat Rycki","Lubelskie (Lublin)","",
			"PL","LSW","Powiat Świdnicki","Lubelskie (Lublin)","",
			"PL","LTM","Powiat Tomaszowski","Lubelskie (Lublin)","",
			"PL","LU","Lublin","Lubelskie (Lublin)","",
			"PL","LUB","Powiat Lubelski","Lubelskie (Lublin)","",
			"PL","LWL","Powiat Włodawski","Lubelskie (Lublin)","",
			"PL","LZ","Zamość","Lubelskie (Lublin)","",
			"PL","LZA","Powiat Zamojski","Lubelskie (Lublin)","",
			"PL","FG","Gorzów Wielkopolski","Lubuskie (Lebus)","",
			"PL","FGW","Powiat Gorzowski","Lubuskie (Lebus)","",
			"PL","FKR","Powiat Krośnieński","Lubuskie (Lebus)","",
			"PL","FMI","Powiat Międzyrzecki","Lubuskie (Lebus)","",
			"PL","FNW","Powiat Nowosolski","Lubuskie (Lebus)","",
			"PL","FSD","Powiat Strzelecko-Drezdenecki","Lubuskie (Lebus)","",
			"PL","FSL","Powiat Słubicki","Lubuskie (Lebus)","",
			"PL","FSU","Powiat Sulęciński","Lubuskie (Lebus)","",
			"PL","FSW","Powiat Świebodziński","Lubuskie (Lebus)","",
			"PL","FWS","Powiat Wschowski","Lubuskie (Lebus)","",
			"PL","FZ","Zielona Góra","Lubuskie (Lebus)","",
			"PL","FZA","Powiat Żarski","Lubuskie (Lebus)","",
			"PL","FZG","Powiat Żagański","Lubuskie (Lebus)","",
			"PL","FZI","Powiat Zielonogórski","Lubuskie (Lebus)","",
			"PL","KBC","Powiat Bocheński","Małopolskie (Kleinpolen)","",
			"PL","KBR","Powiat Brzeski","Małopolskie (Kleinpolen)","",
			"PL","KCH","Powiat Chrzanowski","Małopolskie (Kleinpolen)","",
			"PL","KDA","Powiat Dąbrowski","Małopolskie (Kleinpolen)","",
			"PL","KGR","Powiat Gorlicki","Małopolskie (Kleinpolen)","",
			"PL","KLI","Powiat Limanowski","Małopolskie (Kleinpolen)","",
			"PL","KMI","Powiat Miechowski","Małopolskie (Kleinpolen)","",
			"PL","KMY","Powiat Myślenicki","Małopolskie (Kleinpolen)","",
			"PL","KN","Nowy Sącz","Małopolskie (Kleinpolen)","",
			"PL","KNS","Powiat Nowosądecki","Małopolskie (Kleinpolen)","",
			"PL","KNT","Powiat Nowotarski","Małopolskie (Kleinpolen)","",
			"PL","KOL","Powiat Olkuski","Małopolskie (Kleinpolen)","",
			"PL","KOS","Powiat Oświęcimski","Małopolskie (Kleinpolen)","",
			"PL","KPR","Powiat Proszowicki","Małopolskie (Kleinpolen)","",
			"PL","KR","Kraków","Małopolskie (Kleinpolen)","",
			"PL","KRA","Powiat Krakowski","Małopolskie (Kleinpolen)","",
			"PL","KSU","Powiat Suski","Małopolskie (Kleinpolen)","",
			"PL","KT","Tarnów","Małopolskie (Kleinpolen)","",
			"PL","KTA","Powiat Tarnowski","Małopolskie (Kleinpolen)","",
			"PL","KTT","Powiat Tatrzański","Małopolskie (Kleinpolen)","",
			"PL","KWA","Powiat Wadowicki","Małopolskie (Kleinpolen)","",
			"PL","KWI","Powiat Wielicki","Małopolskie (Kleinpolen)","",
			"PL","WA","Warszawa-Białołęka","Mazowieckie (Masowien)","",
			"PL","WB","Warszawa-Bemowo","Mazowieckie (Masowien)","",
			"PL","WBR","Powiat Białobrzeski","Mazowieckie (Masowien)","",
			"PL","WCI","Powiat Ciechanowski","Mazowieckie (Masowien)","",
			"PL","WD","Warszawa-Bielany","Mazowieckie (Masowien)","",
			"PL","WE","Warszawa-Mokotów","Mazowieckie (Masowien)","",
			"PL","WF","Warszawa-Praga Południe","Mazowieckie (Masowien)","",
			"PL","WG","Powiat Garwoliński","Mazowieckie (Masowien)","",
			"PL","WGM","Powiat Grodziski","Mazowieckie (Masowien)","",
			"PL","WGR","Powiat Grójecki","Mazowieckie (Masowien)","",
			"PL","WGS","Powiat Gostyniński","Mazowieckie (Masowien)","",
			"PL","WH","Warszawa-Praga Północ","Mazowieckie (Masowien)","",
			"PL","WI","Warszawa-Śródmieście","Mazowieckie (Masowien)","",
			"PL","WJ","Warszawa-Targówek","Mazowieckie (Masowien)","",
			"PL","WK","Warszawa-Ursus","Mazowieckie (Masowien)","",
			"PL","WKZ","Powiat Kozienicki","Mazowieckie (Masowien)","",
			"PL","WL","Powiat Legionowski","Mazowieckie (Masowien)","",
			"PL","WLI","Powiat Lipski","Mazowieckie (Masowien)","",
			"PL","WLS","Powiat Łosicki","Mazowieckie (Masowien)","",
			"PL","WM","Powiat Miński","Mazowieckie (Masowien)","",
			"PL","WMA","Powiat Makowski","Mazowieckie (Masowien)","",
			"PL","WML","Powiat Mławski","Mazowieckie (Masowien)","",
			"PL","WN","Warszawa-Ursynów","Mazowieckie (Masowien)","",
			"PL","WND","Powiat Nowodworski","Mazowieckie (Masowien)","",
			"PL","WO","Ostrołęka","Mazowieckie (Masowien)","",
			"PL","WOR","Powiat Ostrowski","Mazowieckie (Masowien)","",
			"PL","WOS","Powiat Ostrołęcki","Mazowieckie (Masowien)","",
			"PL","WOT","Powiat Otwocki","Mazowieckie (Masowien)","",
			"PL","WP","Płock","Mazowieckie (Masowien)","",
			"PL","WPI","Powiat Piaseczyński","Mazowieckie (Masowien)","",
			"PL","WPL","Powiat Płocki","Mazowieckie (Masowien)","",
			"PL","WPN","Powiat Płoński","Mazowieckie (Masowien)","",
			"PL","WPR","Powiat Pruszkowski","Mazowieckie (Masowien)","",
			"PL","WPU","Powiat Pułtuski","Mazowieckie (Masowien)","",
			"PL","WPY","Powiat Przysuski","Mazowieckie (Masowien)","",
			"PL","WPZ","Powiat Przasnyski","Mazowieckie (Masowien)","",
			"PL","WR","Radom","Mazowieckie (Masowien)","",
			"PL","WRA","Powiat Radomski","Mazowieckie (Masowien)","",
			"PL","WS","Siedlce","Mazowieckie (Masowien)","",
			"PL","WSC","Powiat Sochaczewski","Mazowieckie (Masowien)","",
			"PL","WSE","Powiat Sierpecki","Mazowieckie (Masowien)","",
			"PL","WSI","Powiat Siedlecki","Mazowieckie (Masowien)","",
			"PL","WSK","Powiat Sokołowski","Mazowieckie (Masowien)","",
			"PL","WSZ","Powiat Szydłowiecki","Mazowieckie (Masowien)","",
			"PL","WT","Warszawa-Wawer","Mazowieckie (Masowien)","",
			"PL","WU","Warszawa-Ochota","Mazowieckie (Masowien)","",
			"PL","WV","Wołomin","Mazowieckie (Masowien)","",
			"PL","WW-A","Warszawa-Rembertów","Mazowieckie (Masowien)","",
			"PL","WW-F","Warszawa-Wilanów","Mazowieckie (Masowien)","",
			"PL","WW-G","Warszawa-Wilanów","Mazowieckie (Masowien)","",
			"PL","WW-H","Warszawa-Wilanów","Mazowieckie (Masowien)","",
			"PL","WW-J","Warszawa-Wilanów","Mazowieckie (Masowien)","",
			"PL","WW-K","Warszawa-Włochy","Mazowieckie (Masowien)","",
			"PL","WW-M","Warszawa-Włochy","Mazowieckie (Masowien)","",
			"PL","WW-N","Warszawa-Włochy","Mazowieckie (Masowien)","",
			"PL","WW-V","Warszawa-Włochy","Mazowieckie (Masowien)","",
			"PL","WW-W","Warszawa-Wilanów","Mazowieckie (Masowien)","",
			"PL","WW-Y","Warszawa-Wesoła","Mazowieckie (Masowien)","",
			"PL","WWE","Powiat Węgrowski","Mazowieckie (Masowien)","",
			"PL","WWL","Powiat Wołomiński","Mazowieckie (Masowien)","",
			"PL","WWY","Powiat Wyszkowski","Mazowieckie (Masowien)","",
			"PL","WX","Warszawa-Żoliborz","Mazowieckie (Masowien)","",
			"PL","WY","Warszawa-Wola","Mazowieckie (Masowien)","",
			"PL","WZ","Powiat Warszawski Zachodni","Mazowieckie (Masowien)","",
			"PL","WZU","Powiat Żuromiński","Mazowieckie (Masowien)","",
			"PL","WZW","Powiat Zwoleński","Mazowieckie (Masowien)","",
			"PL","WZY","Powiat Żyrardowski","Mazowieckie (Masowien)","",
			"PL","OB","Powiat Brzeski","Opolskie (Oppeln)","",
			"PL","OGL","Powiat Głubczycki","Opolskie (Oppeln)","",
			"PL","OK","Powiat Kędzierzyńsko-Kozielski","Opolskie (Oppeln)","",
			"PL","OKL","Powiat Kluczborski","Opolskie (Oppeln)","",
			"PL","OKR","Powiat Krapkowicki","Opolskie (Oppeln)","",
			"PL","ONA","Powiat Namysłowski","Opolskie (Oppeln)","",
			"PL","ONY","Powiat Nyski","Opolskie (Oppeln)","",
			"PL","OOL","Powiat Oleski","Opolskie (Oppeln)","",
			"PL","OP","Opole","Opolskie (Oppeln)","",
			"PL","OPO","Powiat Opolski","Opolskie (Oppeln)","",
			"PL","OPR","Powiat Prudnicki","Opolskie (Oppeln)","",
			"PL","OST","Powiat Strzelecki","Opolskie (Oppeln)","",
			"PL","RBI","Powiat Bieszczadzki","Podkarpackie (Karpatenvorland)","",
			"PL","RBR","Powiat Brzozowski","Podkarpackie (Karpatenvorland)","",
			"PL","RDE","Powiat Dębicki","Podkarpackie (Karpatenvorland)","",
			"PL","RJA","Powiat Jarosławski","Podkarpackie (Karpatenvorland)","",
			"PL","RJS","Powiat Jasielski","Podkarpackie (Karpatenvorland)","",
			"PL","RK","Krosno","Podkarpackie (Karpatenvorland)","",
			"PL","RKL","Powiat Kolbuszowski","Podkarpackie (Karpatenvorland)","",
			"PL","RKR","Powiat Krośnieński","Podkarpackie (Karpatenvorland)","",
			"PL","RLA","Powiat Łańcucki","Podkarpackie (Karpatenvorland)","",
			"PL","RLE","Powiat Leżajski","Podkarpackie (Karpatenvorland)","",
			"PL","RLS","Powiat Leski","Podkarpackie (Karpatenvorland)","",
			"PL","RLU","Powiat Lubaczowski","Podkarpackie (Karpatenvorland)","",
			"PL","RMI","Powiat Mielecki","Podkarpackie (Karpatenvorland)","",
			"PL","RNI","Powiat Niżański","Podkarpackie (Karpatenvorland)","",
			"PL","RP","Przemyśl","Podkarpackie (Karpatenvorland)","",
			"PL","RPR","Powiat Przemyski","Podkarpackie (Karpatenvorland)","",
			"PL","RPZ","Powiat Przeworski","Podkarpackie (Karpatenvorland)","",
			"PL","RRS","Powiat Ropczycko-Sędziszowski","Podkarpackie (Karpatenvorland)","",
			"PL","RSA","Powiat Sanocki","Podkarpackie (Karpatenvorland)","",
			"PL","RSR","Powiat Strzyżowski","Podkarpackie (Karpatenvorland)","",
			"PL","RST","Powiat Stalowowolski","Podkarpackie (Karpatenvorland)","",
			"PL","RT","Tarnobrzeg","Podkarpackie (Karpatenvorland)","",
			"PL","RTA","Powiat Tarnobrzeski","Podkarpackie (Karpatenvorland)","",
			"PL","RZ","Rzeszów","Podkarpackie (Karpatenvorland)","",
			"PL","RZE","Powiat Rzeszowski","Podkarpackie (Karpatenvorland)","",
			"PL","BAU","Powiat Augustowski","Podlaskie (Podlachien)","",
			"PL","BBI","Powiat Bielski","Podlaskie (Podlachien)","",
			"PL","BGR","Powiat Grajewski","Podlaskie (Podlachien)","",
			"PL","BHA","Powiat Hajnowski","Podlaskie (Podlachien)","",
			"PL","BI","Białystok","Podlaskie (Podlachien)","",
			"PL","BIA","Powiat Białostocki","Podlaskie (Podlachien)","",
			"PL","BKL","Powiat Kolneński","Podlaskie (Podlachien)","",
			"PL","BL","Łomża","Podlaskie (Podlachien)","",
			"PL","BLM","Powiat Łomżyński","Podlaskie (Podlachien)","",
			"PL","BMN","Powiat Moniecki","Podlaskie (Podlachien)","",
			"PL","BS","Suwałki","Podlaskie (Podlachien)","",
			"PL","BSE","Powiat Sejneński","Podlaskie (Podlachien)","",
			"PL","BSI","Powiat Siemiatycki","Podlaskie (Podlachien)","",
			"PL","BSK","Powiat Sokólski","Podlaskie (Podlachien)","",
			"PL","BSU","Powiat Suwalski","Podlaskie (Podlachien)","",
			"PL","BWM","Powiat Wysokomazowiecki","Podlaskie (Podlachien)","",
			"PL","BZA","Powiat Zambrowski","Podlaskie (Podlachien)","",
			"PL","GA","Gdynia","Pomorskie (Pommern)","",
			"PL","GBY","Powiat Bytowski","Pomorskie (Pommern)","",
			"PL","GCH","Powiat Chojnicki","Pomorskie (Pommern)","",
			"PL","GCZ","Powiat Człuchowski","Pomorskie (Pommern)","",
			"PL","GD","Gdańsk","Pomorskie (Pommern)","",
			"PL","GDA","Powiat Gdanski","Pomorskie (Pommern)","",
			"PL","GKA","Powiat Kartuski","Pomorskie (Pommern)","",
			"PL","GKS","Powiat Kościerski","Pomorskie (Pommern)","",
			"PL","GKW","Powiat Kwidzyński","Pomorskie (Pommern)","",
			"PL","GLE","Powiat Lęborski","Pomorskie (Pommern)","",
			"PL","GMB","Powiat Malborski","Pomorskie (Pommern)","",
			"PL","GND","Powiat Nowodworski","Pomorskie (Pommern)","",
			"PL","GPU","Powiat Pucki","Pomorskie (Pommern)","",
			"PL","GS","Słupsk","Pomorskie (Pommern)","",
			"PL","GSL","Powiat Słupski","Pomorskie (Pommern)","",
			"PL","GSP","Sopot","Pomorskie (Pommern)","",
			"PL","GST","Powiat Starogardzki","Pomorskie (Pommern)","",
			"PL","GSZ","Powiat Sztumski","Pomorskie (Pommern)","",
			"PL","GTC","Powiat Tczewski","Pomorskie (Pommern)","",
			"PL","GWE","Powiat Wejherowski","Pomorskie (Pommern)","",
			"PL","SB","Bielsko-Biała","Śląskie (Schlesien)","",
			"PL","SBE","Powiat Będziński","Śląskie (Schlesien)","",
			"PL","SBI","Powiat Bielski","Śląskie (Schlesien)","",
			"PL","SBL","Powiat Bieruńsko-Lędziński","Śląskie (Schlesien)","",
			"PL","SC","Częstochowa","Śląskie (Schlesien)","",
			"PL","SCI","Powiat Cieszyński","Śląskie (Schlesien)","",
			"PL","SCZ","Powiat Częstochowski","Śląskie (Schlesien)","",
			"PL","SD","Dąbrowa Górnicza","Śląskie (Schlesien)","",
			"PL","SG","Gliwice","Śląskie (Schlesien)","",
			"PL","SGL","Powiat Gliwicki","Śląskie (Schlesien)","",
			"PL","SH","Chorzów","Śląskie (Schlesien)","",
			"PL","SI","Siemianowice Śląskie","Śląskie (Schlesien)","",
			"PL","SJ","Jaworzno","Śląskie (Schlesien)","",
			"PL","SJZ","Jastrzębie-Zdrój","Śląskie (Schlesien)","",
			"PL","SK","Katowice","Śląskie (Schlesien)","",
			"PL","SKL","Powiat Kłobucki","Śląskie (Schlesien)","",
			"PL","SL","Ruda Śląska","Śląskie (Schlesien)","",
			"PL","SLU","Powiat Lubliniecki","Śląskie (Schlesien)","",
			"PL","SM","Mysłowice","Śląskie (Schlesien)","",
			"PL","SMI","Powiat Mikołowski","Śląskie (Schlesien)","",
			"PL","SMY","Powiat Myszkowski","Śląskie (Schlesien)","",
			"PL","SO","Sosnowiec","Śląskie (Schlesien)","",
			"PL","SPI","Piekary Śląskie","Śląskie (Schlesien)","",
			"PL","SPS","Powiat Pszczyński","Śląskie (Schlesien)","",
			"PL","SR","Rybnik","Śląskie (Schlesien)","",
			"PL","SRB","Powiat Rybnicki","Śląskie (Schlesien)","",
			"PL","SRC","Powiat Raciborski","Śląskie (Schlesien)","",
			"PL","SRS","früher Ruda Śląska → SL","Śląskie (Schlesien)","",
			"PL","ST","Tychy","Śląskie (Schlesien)","",
			"PL","STA","Powiat Tarnogórski","Śląskie (Schlesien)","",
			"PL","STY","früher Powiat Tyski → SBL","Śląskie (Schlesien)","",
			"PL","SW","Świętochłowice","Śląskie (Schlesien)","",
			"PL","SWD","Powiat Wodzisławski","Śląskie (Schlesien)","",
			"PL","SY","Bytom","Śląskie (Schlesien)","",
			"PL","SZ","Zabrze","Śląskie (Schlesien)","",
			"PL","SZA","Powiat Zawierciański","Śląskie (Schlesien)","",
			"PL","SZO","Żory","Śląskie (Schlesien)","",
			"PL","SZY","Powiat Żywiecki","Śląskie (Schlesien)","",
			"PL","TBU","Powiat Buski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TJE","Powiat Jędrzejowski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TK","Kielce","Świętokrzyskie (Heiligkreuz)","",
			"PL","TKA","Powiat Kazimierski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TKI","Powiat Kielecki","Świętokrzyskie (Heiligkreuz)","",
			"PL","TKN","Powiat Konecki","Świętokrzyskie (Heiligkreuz)","",
			"PL","TLW","Powiat Włoszczowski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TOP","Powiat Opatowski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TOS","Powiat Ostrowiecki","Świętokrzyskie (Heiligkreuz)","",
			"PL","TPI","Powiat Pińczowski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TSA","Powiat Sandomierski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TSK","Powiat Skarżyski","Świętokrzyskie (Heiligkreuz)","",
			"PL","TST","Powiat Starachowicki","Świętokrzyskie (Heiligkreuz)","",
			"PL","TSZ","Powiat Staszowski","Świętokrzyskie (Heiligkreuz)","",
			"PL","NBA","Powiat Bartoszycki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NBR","Powiat Braniewski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NDZ","Powiat Działdowski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NE","Elbląg","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NEB","Powiat Elbląski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NEL","Powiat Ełcki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NGI","Powiat Giżycki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NGO","Powiat Gołdapski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NIL","Powiat Iławski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NKE","Powiat Kętrzyński","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NLI","Powiat Lidzbarski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NMR","Powiat Mrągowski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NNI","Powiat Nidzicki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NNM","Powiat Nowomiejski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NO","Olsztyn","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NOE","Powiat Olecki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NOG","früher Powiat Olecko-Gołdapski (Olecko) → NGO und NOE","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NOL","Olsztyński (Kreis)","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NOS","Powiat Ostródzki","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NPI","Powiat Piski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NSZ","Powiat Szczycieński","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","NWE","Powiat Węgorzewski","Warmińsko-Mazurskie (Ermland-Masuren)","",
			"PL","PCH","Powiat Chodzieski","Wielkopolskie (Großpolen)","",
			"PL","PCT","Powiat Czarnkowsko-Trzcianecki","Wielkopolskie (Großpolen)","",
			"PL","PGN","Powiat Gnieźnieński","Wielkopolskie (Großpolen)","",
			"PL","PGO","Powiat Grodziski","Wielkopolskie (Großpolen)","",
			"PL","PGS","Powiat Gostyński","Wielkopolskie (Großpolen)","",
			"PL","PJA","Powiat Jarociński","Wielkopolskie (Großpolen)","",
			"PL","PK","Kalisz","Wielkopolskie (Großpolen)","",
			"PL","PKA","Powiat Kaliski","Wielkopolskie (Großpolen)","",
			"PL","PKE","Powiat Kępiński","Wielkopolskie (Großpolen)","",
			"PL","PKL","Powiat Kolski","Wielkopolskie (Großpolen)","",
			"PL","PKN","Powiat Koniński","Wielkopolskie (Großpolen)","",
			"PL","PKO","früher Konin → PN","Wielkopolskie (Großpolen)","",
			"PL","PKR","Powiat Krotoszyński","Wielkopolskie (Großpolen)","",
			"PL","PKS","Powiat Kościański","Wielkopolskie (Großpolen)","",
			"PL","PL","Leszno","Wielkopolskie (Großpolen)","",
			"PL","PLE","Powiat Leszczyński","Wielkopolskie (Großpolen)","",
			"PL","PMI","Powiat Międzychodzki","Wielkopolskie (Großpolen)","",
			"PL","PN","Konin","Wielkopolskie (Großpolen)","",
			"PL","PNT","Powiat Nowotomyski","Wielkopolskie (Großpolen)","",
			"PL","PO","Poznań","Wielkopolskie (Großpolen)","",
			"PL","POB","Powiat Obornicki","Wielkopolskie (Großpolen)","",
			"PL","POS","Powiat Ostrowski","Wielkopolskie (Großpolen)","",
			"PL","POT","Powiat Ostrzeszowski","Wielkopolskie (Großpolen)","",
			"PL","POZ","früher Powiat Poznański → PZ","Wielkopolskie (Großpolen)","",
			"PL","PP","Powiat Pilski","Wielkopolskie (Großpolen)","",
			"PL","PPL","Powiat Pleszewski","Wielkopolskie (Großpolen)","",
			"PL","PRA","Powiat Rawicki","Wielkopolskie (Großpolen)","",
			"PL","PSE","Powiat Śremski","Wielkopolskie (Großpolen)","",
			"PL","PSL","Powiat Słupecki","Wielkopolskie (Großpolen)","",
			"PL","PSR","Powiat Średzki","Wielkopolskie (Großpolen)","",
			"PL","PSZ","Powiat Szamotulski","Wielkopolskie (Großpolen)","",
			"PL","PTU","Powiat Turecki","Wielkopolskie (Großpolen)","",
			"PL","PWA","Powiat Wągrowiecki","Wielkopolskie (Großpolen)","",
			"PL","PWL","Powiat Wolsztyński","Wielkopolskie (Großpolen)","",
			"PL","PWR","Powiat Wrzesiński","Wielkopolskie (Großpolen)","",
			"PL","PZ","Powiat Poznański","Wielkopolskie (Großpolen)","",
			"PL","PZL","Powiat Złotowski","Wielkopolskie (Großpolen)","",
			"PL","ZBI","Powiat Białogardzki","Zachodniopomorskie (Westpommern)","",
			"PL","ZCH","Powiat Choszczeński","Zachodniopomorskie (Westpommern)","",
			"PL","ZDR","Powiat Drawski","Zachodniopomorskie (Westpommern)","",
			"PL","ZGL","Powiat Goleniowski","Zachodniopomorskie (Westpommern)","",
			"PL","ZGR","Powiat Gryfiński","Zachodniopomorskie (Westpommern)","",
			"PL","ZGY","Powiat Gryficki","Zachodniopomorskie (Westpommern)","",
			"PL","ZK","Koszalin","Zachodniopomorskie (Westpommern)","",
			"PL","ZKA","Powiat Kamieński","Zachodniopomorskie (Westpommern)","",
			"PL","ZKL","Powiat Kołobrzeski","Zachodniopomorskie (Westpommern)","",
			"PL","ZKO","Powiat Koszaliński","Zachodniopomorskie (Westpommern)","",
			"PL","ZLO","Powiat Łobeski","Zachodniopomorskie (Westpommern)","",
			"PL","ZMY","Powiat Myśliborski","Zachodniopomorskie (Westpommern)","",
			"PL","ZPL","Powiat Policki","Zachodniopomorskie (Westpommern)","",
			"PL","ZPY","Powiat Pyrzycki","Zachodniopomorskie (Westpommern)","",
			"PL","ZS","Szczecin","Zachodniopomorskie (Westpommern)","",
			"PL","ZSD","Powiat Świdwiński","Zachodniopomorskie (Westpommern)","",
			"PL","ZSL","Powiat Sławieński","Zachodniopomorskie (Westpommern)","",
			"PL","ZST","Powiat Stargardzki","Zachodniopomorskie (Westpommern)","",
			"PL","ZSW","Świnoujście","Zachodniopomorskie (Westpommern)","",
			"PL","ZSZ","Powiat Szczecinecki","Zachodniopomorskie (Westpommern)","",
			"PL","ZWA","Powiat Wałecki","Zachodniopomorskie (Westpommern)","",
			"PL","HPA","Polizeihauptkommando","Polizeikennzeichen","",
			"PL","HPB","Woiwodschaft Niederschlesien (Dolnośląskie)","Polizeikennzeichen","",
			"PL","HPC","Woiwodschaft Kujawien-Pommern (Kujawsko-Pomorskie)","Polizeikennzeichen","",
			"PL","HPD","Woiwodschaft Lublin (Lubelskie)","Polizeikennzeichen","",
			"PL","HPE","Woiwodschaft Lebus (Lubuskie)","Polizeikennzeichen","",
			"PL","HPF","Woiwodschaft Łódź (Łódzkie)","Polizeikennzeichen","",
			"PL","HPG","Woiwodschaft Kleinpolen (Małopolskie)","Polizeikennzeichen","",
			"PL","HPH","Woiwodschaft Masowien (Mazowieckie)","Polizeikennzeichen","",
			"PL","HPJ","Woiwodschaft Oppeln (Opolskie)","Polizeikennzeichen","",
			"PL","HPK","Woiwodschaft Karpatenvorland (Podkarpackie)","Polizeikennzeichen","",
			"PL","HPL","Polizeihochschule Szczytno, Polizeischulen Piła, Słupsk und Katowice, Polizeischulzentrum Legionowo","Polizeikennzeichen","",
			"PL","HPM","Woiwodschaft Podlachien (Podlaskie)","Polizeikennzeichen","",
			"PL","HPN","Woiwodschaft Pommern (Pomorskie)","Polizeikennzeichen","",
			"PL","HPP","Woiwodschaft Schlesien (Śląskie)","Polizeikennzeichen","",
			"PL","HPS","Woiwodschaft Heiligenkreuz (Świętokrzyskie)","Polizeikennzeichen","",
			"PL","HPT","Woiwodschaft Ermland-Masuren (Warmińsko-Mazurskie)","Polizeikennzeichen","",
			"PL","HPU","Woiwodschaft Großpolen (Wielkopolskie)","Polizeikennzeichen","",
			"PL","HPW","Woiwodschaft Westpommern (Zachodniopomorskie)","Polizeikennzeichen","",
			"PL","HPZ","Metropolitanpolizeikommando","Polizeikennzeichen","",
			
			"CH", "AI", "Kanton Appenzell Innerrhoden", "", "", "CH", "AR",
			"Kanton Appenzell Ausserrhoden", "", "", "CH", "BE", "Kanton Bern",
			"", "", "CH", "BL", "Kanton Basel-Landschaft", "", "", "CH", "BS",
			"Kanton Basel-Stadt", "", "", "CH", "FR", "Kanton Freiburg", "",
			"", "CH", "GE", "Kanton Genf", "", "", "CH", "GL", "Kanton Glarus",
			"", "", "CH", "GR", "Kanton Graubünden", "", "", "CH", "JU",
			"Kanton Jura", "", "", "CH", "LU", "Kanton Luzern", "", "", "CH",
			"NE", "Kanton Neuenburg", "", "", "CH", "NW", "Kanton Nidwalden",
			"", "", "CH", "OW", "Kanton Obwalden", "", "", "CH", "SG",
			"Kanton St. Gallen", "", "", "CH", "SH", "Kanton Schaffhausen", "",
			"", "CH", "SO", "Kanton Solothurn", "", "", "CH", "SZ",
			"Kanton Schwyz", "", "", "CH", "TG", "Kanton Thurgau", "", "",
			"CH", "TI", "Kanton Tessin", "", "", "CH", "UR", "Kanton Uri", "",
			"", "CH", "VD", "Kanton Waadt", "", "", "CH", "VS",
			"Kanton Wallis", "", "", "CH", "ZG", "Kanton Zug", "", "", "CH",
			"ZH", "Kanton Zürich", "", "", "D", "0", "Regierung", "", "", "D",
			"1", "Bundestagspräsident", "", "", "D", "A",
			"Augsburg, Stadt und Kreis", "Bayern", "", "D", "AA",
			"Ostalbkreis in Aalen, Kreis", "Baden-Württemberg", "", "D", "AB",
			"Aschaffenburg, Stadt und Kreis", "Bayern", "", "D", "ABG",
			"Altenburger Land in Altenburg, Kreis", "Thüringen", "", "D",
			"ABI", "Landkreis Anhalt-Bitterfeld", "Sachsen-Anhalt", "", "D",
			"AC", "Aachen, Stadt", "Nordrhein-Westfalen", "", "D", "AD",
			"Privatfahrzeuge der amerikanischen Streitkräfte", "", "", "D",
			"AE", "Auerbach, Kreis (V)", "Sachsen", "X", "D", "AF",
			"Privatfahrzeuge der amerikanischen Streitkräfte", "", "", "D",
			"AH", "Ahaus, Kreis (BOR)", "Nordrhein-Westfalen", "X", "D", "AIB",
			"Bad Aibling, Kreis (RO)", "Bayern", "X", "D", "AIC",
			"Aichach-Friedberg in Aichach, Kreis", "Bayern", "", "D", "AK",
			"Altenkirchen/Westerwald, Kreis", "Rheinland-Pfalz", "", "D", "AL",
			"Altena, Kreis (MK)", "Nordrhein-Westfalen", "X", "D", "ALF",
			"Alfeld/Leine, Kreis (HI)", "Niedersachsen", "X", "D", "HK",
			"Heidekreis", "Niedersachsen", "", "D", "ALS",
			"Vogelsbergkreis in Alsfeld/Oberhessen, Kreis (VB)", "Hessen", "X",
			"D", "ALZ", "Alzenau i. UFr., Kreis (AB)", "Bayern", "X", "D",
			"AM", "Amberg, Stadt", "Bayern", "", "D", "AN",
			"Ansbach, Stadt und Kreis", "Bayern", "", "D", "ANA",
			"Annaberg, Kreis", "Sachsen", "", "D", "ANG",
			"Angermünde, Kreis (UM)", "Brandenburg", "X", "D", "ANK",
			"Ostvorpommern in Anklam, Kreis (OVP)", "Mecklenburg-Vorpommern",
			"X", "D", "AÖ", "Altötting, Kreis", "Bayern", "", "D", "AP",
			"Weimarer Land in Apolda, Kreis", "Thüringen", "", "D", "APD",
			"Apolda, Kreis (AP)", "Thüringen", "X", "D", "AR",
			"Arnsberg, Kreis (HSK)", "Nordrhein-Westfalen", "X", "D", "ARN",
			"Arnstadt, Kreis (IK)", "Thüringen", "X", "D", "ART",
			"Artern, Kreis (KYF)", "Thüringen", "X", "D", "AS",
			"Amberg-Sulzbach in Amberg, Kreis", "Bayern", "", "D", "ASD",
			"Aschendorf-Hümmling in Papenburg, Kreis (EL)", "Niedersachsen",
			"X", "D", "ASL", "Aschersleben-Staßfurt in Aschersleben, Kreis",
			"Sachsen-Anhalt", "X", "D", "ASZ",
			"Aue-Schwarzenberg in Aue, Kreis", "Sachsen", "", "D", "AT",
			"Altentreptow, Kreis (DM)", "Mecklenburg-Vorpommern", "X", "D",
			"AU", "Aue, Kreis (ASZ)", "Sachsen", "X", "D", "AUR",
			"Aurich, Kreis", "Niedersachsen", "", "D", "AW",
			"Ahrweiler in Bad Neuenahr-Ahrweiler, Kreis", "Rheinland-Pfalz",
			"", "D", "AZ", "Alzey-Worms in Alzey, Kreis", "Rheinland-Pfalz",
			"", "D", "AZE", "Anhalt-Zerbst in Coswig, Kreis", "Sachsen-Anhalt",
			"X", "D", "B", "Berlin", "Berlin", "", "D", "BA",
			"Bamberg, Stadt und Kreis", "Bayern", "", "D", "BAD",
			"Baden-Baden, Stadt", "Baden-Württemberg", "", "D", "BAR",
			"Barnim in Eberswalde, Kreis", "Brandenburg", "", "D", "BB",
			"Böblingen, Kreis", "Baden-Württemberg", "", "D", "BBG",
			"Bernburg, Kreis", "Sachsen-Anhalt", "X", "D", "BC",
			"Biberach/Riß, Kreis", "Baden-Württemberg", "", "D", "BCH",
			"Buchen/Odenwald, Kreis (MOS)", "Baden-Württemberg", "X", "D",
			"BE", "Beckum, Kreis (WAF)", "Nordrhein-Westfalen", "X", "D",
			"BED", "Brand-Erbisdorf, Kreis (FG)", "Sachsen", "X", "D", "BEI",
			"Beilngries, Kreis (EI)", "Bayern", "X", "D", "BEL",
			"Belzig, Kreis (PM)", "Brandenburg", "X", "D", "BER",
			"Bernau, Kreis (BAR)", "Brandenburg", "X", "D", "BF",
			"Steinfurt in Burgsteinfurt, Kreis (ST)", "Nordrhein-Westfalen",
			"X", "D", "BGD", "Berchtesgaden, Kreis (BGL)", "Bayern", "X", "D",
			"BGL", "Berchtesgadener Land in Bad Reichenhall, Kreis", "Bayern",
			"", "D", "BH", "Bühl/Baden, Kreis (RA)", "Baden-Württemberg", "X",
			"D", "BI", "Bielefeld, Stadt", "Nordrhein-Westfalen", "", "D",
			"BID", "Biedenkopf, Kreis (MR)", "Hessen", "X", "D", "BIN",
			"Bingen/Rhein, Kreis (MZ)", "Rheinland-Pfalz", "X", "D", "BIR",
			"Birkenfeld/Nahe, Kreis", "Rheinland-Pfalz", "", "D", "BIT",
			"Bitburg-Prüm in Bitburg, Kreis", "Rheinland-Pfalz", "", "D",
			"BIW", "Bischofswerda, Kreis (BZ)", "Sachsen", "X", "D", "BK",
			"Backnang, Kreis (WN)", "Baden-Württemberg", "X", "D", "BKS",
			"Bernkastel in Bernkastel-Kues, Kreis (WIL)", "Rheinland-Pfalz",
			"X", "D", "BL", "Zollernalbkreis in Balingen, Kreis",
			"Baden-Württemberg", "", "D", "BLB",
			"Wittgenstein in Berleburg, Kreis (SI)", "Nordrhein-Westfalen",
			"X", "D", "BLK", "Burgenlandkreis in Naumburg, Kreis",
			"Sachsen-Anhalt", "X", "D", "BM", "Erftkreis in Bergheim, Kreis",
			"Nordrhein-Westfalen", "", "D", "BN", "Bonn, Stadt",
			"Nordrhein-Westfalen", "", "D", "BNA", "Borna, Kreis (L)",
			"Sachsen", "X", "D", "BO", "Bochum, Stadt", "Nordrhein-Westfalen",
			"", "D", "BÖ", "Bördekreis in Oschersleben, Kreis",
			"Sachsen-Anhalt", "X", "D", "BK",
			"Bördekreis in Oschersleben, Kreis", "Sachsen-Anhalt", "", "D",
			"BOG", "Bogen, Kreis (SR)", "Bayern", "X", "D", "BOH",
			"Bocholt, Stadt (BOR)", "Nordrhein-Westfalen", "X", "D", "BOR",
			"Borken, Kreis", "Nordrhein-Westfalen", "", "D", "BOT",
			"Bottrop, Stadt", "Nordrhein-Westfalen", "", "D", "BR",
			"Bruchsal, Kreis (KA)", "Baden-Württemberg", "X", "D", "BRA",
			"Wesermarsch in Brake/Unterweser, Kreis", "Niedersachsen", "", "D",
			"BRB", "Brandenburg, Stadt", "Brandenburg", "", "D", "BRG",
			"Burg, Kreis (JL)", "Sachsen-Anhalt", "X", "D", "BRI",
			"Brilon, Kreis (HSK)", "Nordrhein-Westfalen", "X", "D", "BRK",
			"Bad Brückenau, Kreis (KG)", "Bayern", "X", "D", "BRL",
			"Blankenburg in Braunlage, Kreis (GS)", "Niedersachsen", "X", "D",
			"BRV", "Bremervörde, Kreis (ROW)", "Niedersachsen", "X", "D", "BS",
			"Braunschweig, Stadt", "Niedersachsen", "", "D", "BSB",
			"Bersenbrück, Kreis (OS)", "Niedersachsen", "X", "D", "BSK",
			"Beeskow, Kreis (LOS)", "Brandenburg", "X", "D", "BT",
			"Bayreuth, Stadt und Kreis", "Bayern", "", "D", "BTF",
			"Bitterfeld, Kreis", "Sachsen-Anhalt", "X", "D", "BU",
			"Burgdorf, Kreis (H)", "Niedersachsen", "X", "D", "BÜD",
			"Büdingen/Oberhessen, Kreis (FB)", "Hessen", "X", "D", "BUL",
			"Burglengenfeld, Kreis (SAD)", "Bayern", "X", "D", "BÜR",
			"Büren, Kreis (PB)", "Nordrhein-Westfalen", "X", "D", "BÜS",
			"Konstanz, Kreis, Gemeinde Büsingen / Hochrhein",
			"Baden-Württemberg", "", "D", "BÜZ", "Bützow, Kreis (GÜ)",
			"Mecklenburg-Vorpommern", "X", "D", "BZ", "Bautzen, Kreis",
			"Sachsen", "", "D", "BZA", "Bergzabern, Kreis (SÜW)",
			"Rheinland-Pfalz", "X", "D", "C", "Chemnitz, Stadt", "Sachsen", "",
			"D", "CA", "Calau, Kreis (OSL)", "Brandenburg", "X", "D", "CAS",
			"Castrop-Rauxel, Stadt (RE)", "Nordrhein-Westfalen", "X", "D",
			"CB", "Cottbus, Stadt", "Brandenburg", "", "D", "CE",
			"Celle, Kreis", "Niedersachsen", "", "D", "CHA", "Cham, Kreis",
			"Bayern", "", "D", "CLP", "Cloppenburg, Kreis", "Niedersachsen",
			"", "D", "CLZ", "Zellerfeld in Clausthal-Zellerfeld, Kreis (GS)",
			"Niedersachsen", "X", "D", "CO", "Coburg, Stadt und Kreis",
			"Bayern", "", "D", "COC", "Cochem-Zell in Cochem, Kreis",
			"Rheinland-Pfalz", "", "D", "COE", "Coesfeld, Kreis",
			"Nordrhein-Westfalen", "", "D", "CR", "Crailsheim, Kreis (SHA)",
			"Baden-Württemberg", "X", "D", "CUX", "Cuxhaven, Kreis",
			"Niedersachsen", "", "D", "CW", "Calw, Kreis", "Baden-Württemberg",
			"", "D", "D", "Düsseldorf, Stadt", "Nordrhein-Westfalen", "", "D",
			"DA", "Darmstadt, Stadt", "Hessen", "", "D", "DAH",
			"Dachau, Kreis", "Bayern", "", "D", "DAN",
			"Lüchow-Dannenberg in Lüchow, Kreis", "Niedersachsen", "", "D",
			"DAU", "Daun, Kreis", "Rheinland-Pfalz", "", "D", "DBR",
			"Bad Doberan, Kreis", "Mecklenburg-Vorpommern", "", "D", "DD",
			"Dresden, Stadt", "Sachsen", "", "D", "DE", "Dessau, Stadt",
			"Sachsen-Anhalt", "X", "D", "DEG", "Deggendorf, Kreis", "Bayern",
			"", "D", "DEL", "Delmenhorst, Stadt", "Niedersachsen", "", "D",
			"DGF", "Dingolfing-Landau in Dingolfing, Kreis", "Bayern", "", "D",
			"DH", "Diepholz, Kreis", "Niedersachsen", "", "D", "DI",
			"Dieburg, Kreis (DA)", "Hessen", "X", "D", "DIL",
			"Dillkreis in Dillenburg, Kreis (LDK)", "Hessen", "X", "D", "DIN",
			"Dinslaken, Kreis (WES)", "Nordrhein-Westfalen", "X", "D", "DIZ",
			"Unterlahnkreis in Diez, Kreis (EMS)", "Rheinland-Pfalz", "X", "D",
			"DKB", "Dinkelsbühl, Kreis (AN)", "Bayern", "X", "D", "DL",
			"Döbeln, Kreis", "Sachsen", "", "D", "DLG",
			"Dillingen a. d. Donau, Kreis", "Bayern", "", "D", "DM",
			"Demmin, Kreis", "Mecklenburg-Vorpommern", "", "D", "DN",
			"Düren, Kreis", "Nordrhein-Westfalen", "", "D", "DO",
			"Dortmund, Stadt", "Nordrhein-Westfalen", "", "D", "DON",
			"Donau-Ries in Donauwörth, Kreis", "Bayern", "", "D", "DS",
			"Donaueschingen, Kreis (VS)", "Baden-Württemberg", "X", "D", "DT",
			"Lippe in Detmold, Kreis (LIP)", "Nordrhein-Westfalen", "X", "D",
			"DU", "Duisburg, Stadt", "Nordrhein-Westfalen", "", "D", "DUD",
			"Duderstadt, Kreis (GÖ)", "Niedersachsen", "X", "D", "DÜW",
			"Bad Dürkheim/Weinstraße, Kreis", "Rheinland-Pfalz", "", "D", "DW",
			"Weißeritzkreis in Dippoldiswalde, Kreis", "Sachsen", "", "D",
			"DZ", "Delitzsch, Kreis", "Sachsen", "", "D", "E", "Essen, Stadt",
			"Nordrhein-Westfalen", "", "D", "EA", "Eisenach, Stadt",
			"Thüringen", "", "D", "EB", "Eilenburg, Kreis (DZ)", "Sachsen",
			"X", "D", "EBE", "Ebersberg, Kreis", "Bayern", "", "D", "EBN",
			"Ebern, Kreis (HAS)", "Bayern", "X", "D", "EBS",
			"Ebermannstadt, Kreis (FO)", "Bayern", "X", "D", "ECK",
			"Eckernförde, Kreis (RD)", "Schleswig-Holstein", "X", "D", "ED",
			"Erding, Kreis", "Bayern", "", "D", "EE",
			"Elbe-Elster in Bad Liebenwerda, Kreis", "Brandenburg", "", "D",
			"EF", "Erfurt, Stadt", "Thüringen", "", "D", "EG",
			"Eggenfelden, Kreis (PAN)", "Bayern", "X", "D", "EH",
			"Eisenhüttenstadt, Stadt und Kreis (LOS)", "Brandenburg", "X", "D",
			"EHI", "Ehingen/Donau, Kreis (UL)", "Baden-Württemberg", "X", "D",
			"EI", "Eichstätt, Kreis", "Bayern", "", "D", "EIC",
			"Eichsfeld in Heiligenstadt, Kreis", "Thüringen", "", "D", "EIH",
			"Eichstätt, Kreis (EI)", "Bayern", "X", "D", "EIL",
			"Eisleben, Kreis (ML)", "Sachsen-Anhalt", "X", "D", "EIN",
			"Einbeck, Kreis (NOM)", "Niedersachsen", "X", "D", "EIS",
			"Eisenberg, Kreis (SHK)", "Thüringen", "X", "D", "EL",
			"Emsland in Meppen, Kreis", "Niedersachsen", "", "D", "EM",
			"Emmendingen, Kreis", "Baden-Württemberg", "", "D", "EMD",
			"Emden, Stadt", "Niedersachsen", "", "D", "EMS",
			"Rhein-Lahn-Kreis in Bad Ems, Kreis", "Rheinland-Pfalz", "", "D",
			"EN", "Ennepe-Ruhr-Kreis in Schwelm, Kreis", "Nordrhein-Westfalen",
			"", "D", "ER", "Erlangen, Stadt", "Bayern", "", "D", "ERB",
			"Odenwaldkreis in Erbach/Odenwald, Kreis", "Hessen", "", "D",
			"ERH", "Erlangen-Höchstadt in Erlangen, Kreis", "Bayern", "", "D",
			"ERK", "Erkelenz, Kreis (HS)", "Nordrhein-Westfalen", "X", "D",
			"TDO", "Nordsachsen", "Sachsen", "", "D", "ERZ", "Erzgebirgskreis",
			"Sachsen", "", "D", "ES", "Esslingen/Neckar, Kreis",
			"Baden-Württemberg", "", "D", "ESA", "Eisenach, Kreis (WAK)",
			"Thüringen", "X", "D", "ESB", "Eschenbach i. d. OPf., Kreis (NEW)",
			"Bayern", "X", "D", "ESW",
			"Werra-Meißner-Kreis in Eschwege, Kreis", "Hessen", "", "D", "EU",
			"Euskirchen, Kreis", "Nordrhein-Westfalen", "", "D", "EUT",
			"Eutin, Kreis (OH)", "Schleswig-Holstein", "X", "D", "EW",
			"Eberswalde, Kreis (BAR)", "Brandenburg", "X", "D", "F",
			"Frankfurt/Main, Stadt", "Hessen", "", "D", "FAL",
			"Fallingbostel, Kreis (SFA)", "Niedersachsen", "X", "D", "FB",
			"Wetteraukreis in Friedberg/Hessen, Kreis", "Hessen", "", "D",
			"FD", "Fulda, Kreis", "Hessen", "", "D", "FDB",
			"Friedberg, Kreis (AIC)", "Bayern", "X", "D", "FDS",
			"Freudenstadt, Kreis", "Baden-Württemberg", "", "D", "FEU",
			"Feuchtwangen, Kreis (AN)", "Bayern", "X", "D", "FF",
			"Frankfurt (Oder), Stadt", "Brandenburg", "", "D", "FFB",
			"Fürstenfeldbruck, Kreis", "Bayern", "", "D", "FG",
			"Freiberg, Kreis", "Sachsen", "", "D", "FH",
			"Main-Taunus-Kreis in Frankfurt/M.-Höchst, Kreis (MTK)", "Hessen",
			"X", "D", "FI", "Finsterwalde, Kreis (EE)", "Brandenburg", "X",
			"D", "FKB", "Frankenberg/Eder, Kreis (KB)", "Hessen", "X", "D",
			"FL", "Flensburg, Stadt", "Schleswig-Holstein", "", "D", "FLÖ",
			"Flöha, Kreis (FG)", "Sachsen", "X", "D", "FN",
			"Bodenseekreis in Friedrichshafen, Kreis", "Baden-Württemberg", "",
			"D", "FO", "Forchheim, Kreis", "Bayern", "", "D", "FOR",
			"Forst, Kreis (SPN)", "Brandenburg", "X", "D", "FR",
			"Freiburg/Breisgau, Stadt", "Baden-Württemberg", "", "D", "FRG",
			"Freyung-Grafenau in Freyung, Kreis", "Bayern", "", "D", "FRI",
			"Friesland in Jever, Kreis", "Niedersachsen", "", "D", "FRW",
			"Bad Freienwalde, Kreis (MOL)", "Brandenburg", "X", "D", "FS",
			"Freising, Kreis", "Bayern", "", "D", "FT",
			"Frankenthal/Pfalz, Stadt", "Rheinland-Pfalz", "", "D", "FTL",
			"Freital, Kreis (DW)", "Sachsen", "X", "D", "FÜ",
			"Fürth, Stadt und Kreis", "Bayern", "", "D", "FÜS",
			"Füssen, Kreis (OAL)", "Bayern", "X", "D", "FW",
			"Fürstenwalde, Kreis (LOS)", "Brandenburg", "X", "D", "FZ",
			"Fritzlar-Homberg in Fritzlar, Kreis (HR)", "Hessen", "X", "D",
			"G", "Gera, Stadt", "Thüringen", "", "D", "GA",
			"Gardelegen, Kreis (SAW)", "Sachsen-Anhalt", "X", "D", "GAN",
			"Gandersheim in Bad Gandersheim, Kreis (NOM)", "Niedersachsen",
			"X", "D", "GAP", "Garmisch-Partenkirchen, Kreis", "Bayern", "",
			"D", "GC", "Chemnitzer Land in Glauchau, Kreis", "Sachsen", "",
			"D", "GD", "Schwäbisch Gmünd, Kreis (AA)", "Baden-Württemberg",
			"X", "D", "GDB", "Gadebusch, Kreis (NWM)",
			"Mecklenburg-Vorpommern", "X", "D", "GE", "Gelsenkirchen, Stadt",
			"Nordrhein-Westfalen", "", "D", "GEL", "Geldern, Kreis (KLE)",
			"Nordrhein-Westfalen", "X", "D", "GEM",
			"Gemünden a. Main, Kreis (MSP)", "Bayern", "X", "D", "GEO",
			"Gerolzhofen, Kreis (SW)", "Bayern", "X", "D", "GER",
			"Germersheim, Kreis", "Rheinland-Pfalz", "", "D", "GF",
			"Gifhorn, Kreis", "Niedersachsen", "", "D", "GG",
			"Groß-Gerau, Kreis", "Hessen", "", "D", "GHA",
			"Geithain, Kreis (L)", "Sachsen", "X", "D", "GHC",
			"Gräfenhainichen, Kreis (WB)", "Sachsen-Anhalt", "X", "D", "GI",
			"Gießen, Kreis", "Hessen", "", "D", "GK",
			"Geilenkirchen-Heinsberg, Kreis (HS)", "Nordrhein-Westfalen", "X",
			"D", "GL",
			"Rheinisch-Bergischer Kreis in Bergisch-Gladbach, Kreis",
			"Nordrhein-Westfalen", "", "D", "GLA", "Gladbeck, Stadt (RE)",
			"Nordrhein-Westfalen", "X", "D", "GM",
			"Oberbergischer Kreis in Gummersbach, Kreis",
			"Nordrhein-Westfalen", "", "D", "GMN", "Grimmen, Kreis (NVP)",
			"Mecklenburg-Vorpommern", "X", "D", "GN", "Gelnhausen, Kreis (HU)",
			"Hessen", "X", "D", "GNT", "Genthin, Kreis (JL)", "Sachsen-Anhalt",
			"X", "D", "GÖ", "Göttingen, Stadt und Kreis", "Niedersachsen", "",
			"D", "GOA", "Sankt Goar, Kreis (SIM)", "Rheinland-Pfalz", "X", "D",
			"GOH", "Sankt Goarshausen, Kreis (EMS)", "Rheinland-Pfalz", "X",
			"D", "GP", "Göppingen, Kreis", "Baden-Württemberg", "", "D", "GR",
			"Görlitz, Stadt", "Sachsen", "", "D", "GRA",
			"Grafenau, Kreis (FRG)", "Bayern", "X", "D", "GRH",
			"Großenhain, Kreis (RG)", "Sachsen", "X", "D", "GRI",
			"Griesbach i. Rottal, Kreis (PA)", "Bayern", "X", "D", "GRM",
			"Grimma, Kreis (MTL)", "Sachsen", "X", "D", "GRS",
			"Gransee, Kreis (OHV)", "Brandenburg", "X", "D", "GRZ",
			"Greiz, Kreis", "Thüringen", "", "D", "GS", "Goslar, Kreis",
			"Niedersachsen", "", "D", "GT", "Gütersloh, Kreis",
			"Nordrhein-Westfalen", "", "D", "GTH", "Gotha, Kreis", "Thüringen",
			"", "D", "GÜ", "Güstrow, Kreis", "Mecklenburg-Vorpommern", "", "D",
			"GUB", "Guben, Kreis (SPN)", "Brandenburg", "X", "D", "GUN",
			"Gunzenhausen, Kreis (WUG)", "Bayern", "X", "D", "GV",
			"Grevenbroich, Kreis (NE)", "Nordrhein-Westfalen", "X", "D", "GVM",
			"Grevesmühlen, Kreis (NWM)", "Mecklenburg-Vorpommern", "X", "D",
			"GW", "Greifswald, Kreis (OVP)", "Mecklenburg-Vorpommern", "X",
			"D", "GZ", "Günzburg, Kreis", "Bayern", "", "D", "H",
			"Hannover, Stadt und Kreis", "Niedersachsen", "", "D", "HA",
			"Hagen, Stadt", "Nordrhein-Westfalen", "", "D", "HAB",
			"Hammelburg, Kreis (KG)", "Bayern", "X", "D", "HAL",
			"Halle, Stadt", "Sachsen-Anhalt", "X", "D", "HAM", "Hamm, Stadt",
			"Nordrhein-Westfalen", "", "D", "HAS",
			"Haßberge in Haßfurt, Kreis", "Bayern", "", "D", "HB",
			"Hansestadt Bremen, Bremerhaven, Stadt", "Bremen", "", "D", "HBN",
			"Hildburghausen, Kreis", "Thüringen", "", "D", "HBS",
			"Halberstadt, Kreis", "Sachsen-Anhalt", "X", "D", "HC",
			"Hainichen, Kreis (MW)", "Sachsen", "X", "D", "HCH",
			"Hechingen, Kreis (BL)", "Baden-Württemberg", "X", "D", "HD",
			"Heidelberg, Stadt, Rhein-Neckar-Kreis", "Baden-Württemberg", "",
			"D", "HDH", "Heidenheim/Brenz, Kreis", "Baden-Württemberg", "",
			"D", "HDL", "Haldensleben, Kreis (OK)", "Sachsen-Anhalt", "X", "D",
			"HE", "Helmstedt, Kreis", "Niedersachsen", "", "D", "HEB",
			"Hersbruck, Kreis (LAU)", "Bayern", "X", "D", "HEF",
			"Hersfeld-Rotenburg in Bad Hersfeld, Kreis", "Hessen", "", "D",
			"HEI", "Dithmarschen in Heide/Holstein, Kreis",
			"Schleswig-Holstein", "", "D", "HER", "Herne, Stadt",
			"Nordrhein-Westfalen", "", "D", "HET", "Hettstedt, Kreis (ML)",
			"Sachsen-Anhalt", "X", "D", "HF", "Herfordin Kirchlengern, Kreis",
			"Nordrhein-Westfalen", "", "D", "HG",
			"Hochtaunuskreis in Bad Homburg vor der Höhe, Kreis", "Hessen", "",
			"D", "HGN", "Hagenow, Kreis (LWL)", "Mecklenburg-Vorpommern", "X",
			"D", "HGW", "Hansestadt Greifswald", "Mecklenburg-Vorpommern", "",
			"D", "HH", "Hansestadt Hamburg", "Hamburg", "", "D", "HHM",
			"Hohenmölsen, Kreis (WSF)", "Sachsen-Anhalt", "X", "D", "HI",
			"Hildesheim, Kreis", "Niedersachsen", "", "D", "HIG",
			"Heiligenstadt, Kreis (EIC)", "Thüringen", "X", "D", "HIP",
			"Hilpoltstein, Kreis (RH)", "Bayern", "X", "D", "HL",
			"Hansestadt Lübeck", "Schleswig-Holstein", "", "D", "HM",
			"Hameln-Pyrmont in Hameln, Kreis", "Niedersachsen", "", "D", "HMÜ",
			"Münden, Kreis (GÖ)", "Niedersachsen", "X", "D", "HN",
			"Heilbronn/Neckar, Stadt und Kreis", "Baden-Württemberg", "", "D",
			"HO", "Hof, Stadt und Kreis", "Bayern", "", "D", "HOG",
			"Hofgeismar, Kreis (KS)", "Hessen", "X", "D", "HOH",
			"Hofheim i. UFr., Kreis (HAS)", "Bayern", "X", "D", "HOL",
			"Holzminden, Kreis", "Niedersachsen", "", "D", "HOM",
			"Saarpfalz-Kreis in Homburg/Saar, Kreis", "Saarland", "", "D",
			"HOR", "Horb/Neckar, Kreis (FDS)", "Baden-Württemberg", "X", "D",
			"HÖS", "Höchstadt a. d. Aisch, Kreis (ERH)", "Bayern", "X", "D",
			"HOT", "Hohenstein-Ernstthal, Kreis (GC)", "Sachsen", "X", "D",
			"HP", "Bergstraße in Heppenheim/Bergstraße, Kreis", "Hessen", "",
			"D", "HR", "Schwalm-Eder-Kreis in Homberg, Kreis", "Hessen", "",
			"D", "HRO", "Hansestadt Rostock", "Mecklenburg-Vorpommern", "",
			"D", "HS", "Heinsberg, Kreis", "Nordrhein-Westfalen", "", "D",
			"HSK", "Hochsauerlandkreis in Meschede, Kreis",
			"Nordrhein-Westfalen", "", "D", "HST", "Hansestadt Stralsund",
			"Mecklenburg-Vorpommern", "", "D", "HU",
			"Main-Kinzig-Kreis in Hanau, Kreis", "Hessen", "", "D", "HÜN",
			"Hünfeld, Kreis (FD)", "Hessen", "X", "D", "HUS",
			"Husum, Kreis (NF)", "Schleswig-Holstein", "X", "D", "HV",
			"Havelberg, Kreis (SDL)", "Sachsen-Anhalt", "X", "D", "HVL",
			"Havelland in Rathenow, Kreis", "Brandenburg", "", "D", "HW",
			"Halle, Kreis (GT)", "Nordrhein-Westfalen", "X", "D", "HWI",
			"Hansestadt Wismar", "Mecklenburg-Vorpommern", "", "D", "HX",
			"Höxter, Kreis", "Nordrhein-Westfalen", "", "D", "HY",
			"Hoyerswerda, Stadt", "Sachsen", "", "D", "HZ",
			"Herzberg, Kreis (EE)", "Brandenburg", "X", "D", "HZ",
			"Landkreis Harz", "Sachsen-Anhalt", "", "D", "IGB",
			"St. Ingbert, Stadt", "Saarland", "", "D", "IK",
			"Ilm-Kreis in Arnstadt, Kreis", "Thüringen", "", "D", "IL",
			"Ilmenau, Kreis (IK)", "Thüringen", "X", "D", "ILL",
			"Illertissen, Kreis (NU)", "Bayern", "X", "D", "IN",
			"Ingolstadt, Stadt", "Bayern", "", "D", "IS",
			"Iserlohn, Stadt und Kreis (MK)", "Nordrhein-Westfalen", "X", "D",
			"IZ", "Steinburg in Itzehoe, Kreis", "Schleswig-Holstein", "", "D",
			"J", "Jena, Stadt", "Thüringen", "", "D", "JB",
			"Jüterbog, Kreis (TF)", "Brandenburg", "X", "D", "JE",
			"Jessen, Kreis (WB)", "Sachsen-Anhalt", "X", "D", "JEV",
			"Friesland in Jever, Kreis (FRI)", "Niedersachsen", "X", "D", "JL",
			"Jerichower Land in Burg, Kreis", "Sachsen-Anhalt", "X", "D",
			"JÜL", "Jülich, Kreis (DN)", "Nordrhein-Westfalen", "X", "D", "K",
			"Köln, Stadt", "Nordrhein-Westfalen", "", "D", "KA",
			"Karlsruhe, Stadt und Kreis", "Baden-Württemberg", "", "D", "KAR",
			"Main-Spessart in Karlstadt, Kreis (MSP)", "Bayern", "X", "D",
			"KB", "Waldeck-Frankenberg in Korbach, Kreis", "Hessen", "", "D",
			"KC", "Kronach, Kreis", "Bayern", "", "D", "KE",
			"Kempten (Allgäu), Stadt", "Bayern", "", "D", "KEH",
			"Kelheim, Kreis", "Bayern", "", "D", "KEL", "Kehl, Kreis (OG)",
			"Baden-Württemberg", "X", "D", "KEM", "Kemnath, Kreis (TIR)",
			"Bayern", "X", "D", "KF", "Kaufbeuren, Stadt", "Bayern", "", "D",
			"KG", "Bad Kissingen, Kreis", "Bayern", "", "D", "KH",
			"Bad Kreuznach, Stadt und Kreis", "Rheinland-Pfalz", "", "D", "KI",
			"Kiel, Stadt", "Schleswig-Holstein", "", "D", "KIB",
			"Donnersbergkreis in Kirchheimbolanden, Kreis", "Rheinland-Pfalz",
			"", "D", "KK", "Kempen-Krefeld in Kempen, Kreis (VIE)",
			"Nordrhein-Westfalen", "X", "D", "KL",
			"Kaiserslautern, Stadt und Kreis", "Rheinland-Pfalz", "", "D",
			"KLE", "Kleve, Kreis", "Nordrhein-Westfalen", "", "D", "KLZ",
			"Klötze, Kreis (SAW)", "Sachsen-Anhalt", "X", "D", "KM",
			"Kamenz, Kreis", "Sachsen", "", "D", "KN", "Konstanz, Kreis",
			"Baden-Württemberg", "", "D", "KO", "Koblenz, Stadt",
			"Rheinland-Pfalz", "", "D", "KÖN",
			"Königshofen i. Grabfeld, Kreis (NES)", "Bayern", "X", "D", "KÖT",
			"Köthen, Kreis", "Sachsen-Anhalt", "X", "D", "KÖZ",
			"Kötzting, Kreis (CHA)", "Bayern", "X", "D", "KR",
			"Krefeld, Stadt", "Nordrhein-Westfalen", "", "D", "KRU",
			"Krumbach, Kreis (GZ)", "Bayern", "X", "D", "KS",
			"Kassel, Stadt und Kreis", "Hessen", "", "D", "KT",
			"Kitzingen, Kreis", "Bayern", "", "D", "KU", "Kulmbach, Kreis",
			"Bayern", "", "D", "KÜN", "Hohenlohekreis in Künzelsau, Kreis",
			"Baden-Württemberg", "", "D", "KUS", "Kusel, Kreis",
			"Rheinland-Pfalz", "", "D", "KW",
			"Königs Wusterhausen, Kreis (LDS)", "Brandenburg", "X", "D", "KY",
			"Kyritz, Kreis (OPR)", "Brandenburg", "X", "D", "KYF",
			"Kyffhäuserkreis in Sondershausen, Kreis", "Thüringen", "", "D",
			"L", "Leipzig, Stadt, Leipziger Land in Leipzig, Kreis", "Sachsen",
			"", "D", "L", "Lahn-Dill-Kreis in Wetzlar, Kreis (LDK, GI)",
			"Hessen", "X", "D", "LA", "Landshut, Stadt und Kreis", "Bayern",
			"", "D", "LAN", "Landau a. d. Isar, Kreis (DGF)", "Bayern", "X",
			"D", "LAT", "Vogelsbergkreis in Lauterbach/Hessen, Kreis (VB)",
			"Hessen", "X", "D", "LAU",
			"Nürnberger Land in Lauf a. d. Pegnitz, Kreis", "Bayern", "", "D",
			"LB", "Ludwigsburg, Kreis", "Baden-Württemberg", "", "D", "LBS",
			"Lobenstein, Kreis (SOK)", "Thüringen", "X", "D", "LBZ",
			"Lübz, Kreis (PCH)", "Mecklenburg-Vorpommern", "X", "D", "LC",
			"Luckau, Kreis (LDS)", "Brandenburg", "X", "D", "LD",
			"Landau, Stadt", "Rheinland-Pfalz", "", "D", "LDK",
			"Lahn-Dill-Kreis in Wetzlar, Kreis", "Hessen", "", "D", "LDS",
			"Dahme-Spreewald in Königs Wusterhausen, Kreis", "Brandenburg", "",
			"D", "LE", "Lemgo, Kreis (LIP)", "Nordrhein-Westfalen", "X", "D",
			"LEO", "Leonberg/Württemberg, Kreis (BB)", "Baden-Württemberg",
			"X", "D", "LER", "Leer in Leer (Ostfriesland), Kreis",
			"Niedersachsen", "", "D", "LEV", "Leverkusen, Stadt",
			"Nordrhein-Westfalen", "", "D", "LF", "Laufen, Kreis (BGL)",
			"Bayern", "X", "D", "LG", "Lüneburg, Kreis", "Niedersachsen", "",
			"D", "LH", "Lüdinghausen, Kreis (COE)", "Nordrhein-Westfalen", "X",
			"D", "LI", "Lindau (Bodensee), Kreis", "Bayern", "", "D", "LIB",
			"Bad Liebenwerda, Kreis (EE)", "Brandenburg", "X", "D", "LIF",
			"Lichtenfels, Kreis", "Bayern", "", "D", "LIN",
			"Lingen in Lingen (Ems), Kreis (EL)", "Niedersachsen", "X", "D",
			"LIP", "Lippe in Detmold, Kreis", "Nordrhein-Westfalen", "", "D",
			"LK", "Lübbecke, Kreis (MI)", "Nordrhein-Westfalen", "X", "D",
			"LL", "Landsberg a. Lech, Kreis", "Bayern", "", "D", "LM",
			"Limburg-Weilburg in Limburg-Lahn, Kreis", "Hessen", "", "D", "LN",
			"Lübben, Kreis (LDS)", "Brandenburg", "X", "D", "LÖ",
			"Lörrach, Kreis", "Baden-Württemberg", "", "D", "LÖB",
			"Löbau, Kreis (ZI)", "Sachsen", "X", "D", "LOH",
			"Lohr a. Main, Kreis (MSP)", "Bayern", "X", "D", "LOS",
			"Oder-Spree in Beeskow, Kreis", "Brandenburg", "", "D", "LP",
			"Lippstadt, Kreis (SO)", "Nordrhein-Westfalen", "X", "D", "LR",
			"Lahr/Schwarzwald, Kreis (OG)", "Baden-Württemberg", "X", "D",
			"LS", "Märkischer Kreis in Lüdenscheid, Kreis (MK)",
			"Nordrhein-Westfalen", "X", "D", "LSZ",
			"Bad Langensalza, Kreis (UH)", "Thüringen", "X", "D", "LU",
			"Ludwigshafen Rhein, Stadt und Kreis", "Rheinland-Pfalz", "", "D",
			"LÜD", "Lüdenscheid, Kreis (MK)", "Nordrhein-Westfalen", "X", "D",
			"LUK", "Luckenwalde, Kreis (TF)", "Brandenburg", "X", "D", "LÜN",
			"Lünen, Stadt (UN)", "Nordrhein-Westfalen", "X", "D", "LWL",
			"Ludwigslust, Kreis", "Mecklenburg-Vorpommern", "", "D", "M",
			"München, Stadt und Kreis", "Bayern", "", "D", "MA",
			"Mannheim, Stadt", "Baden-Württemberg", "", "D", "MAB",
			"Marienberg, Kreis (MEK)", "Sachsen", "X", "D", "MAI",
			"Mainburg, Kreis (KEH)", "Bayern", "X", "D", "MAK",
			"Marktredwitz, Stadt (WUN)", "Bayern", "X", "D", "MAL",
			"Mallersdorf, Kreis (SR)", "Bayern", "X", "D", "MAR",
			"Marktheidenfeld, Kreis (MSP)", "Bayern", "X", "D", "MB",
			"Miesbach, Kreis", "Bayern", "", "D", "MC", "Malchin, Kreis (DM)",
			"Mecklenburg-Vorpommern", "X", "D", "MD", "Magdeburg, Stadt",
			"Sachsen-Anhalt", "X", "D", "ME", "Mettmann, Kreis",
			"Nordrhein-Westfalen", "", "D", "MED",
			"Süderdithmarschen in Meldorf/Holstein, Kreis (HEI)",
			"Schleswig-Holstein", "X", "D", "MEG", "Melsungen, Kreis (HR)",
			"Hessen", "X", "D", "MEI", "Meißen, Kreis", "Sachsen", "", "D",
			"MEK", "Mittlerer Erzgebirgskreis in Marienberg, Kreis", "Sachsen",
			"", "D", "MEL", "Melle, Kreis (OS)", "Niedersachsen", "X", "D",
			"MEP", "Meppen, Kreis (EL)", "Niedersachsen", "X", "D", "MER",
			"Merseburg, Kreis (MQ)", "Sachsen-Anhalt", "X", "D", "MES",
			"Hochsauerlandkreis in Meschede, Kreis (HSK)",
			"Nordrhein-Westfalen", "X", "D", "MET",
			"Mellrichstadt, Kreis (NES)", "Bayern", "X", "D", "MG",
			"Mönchengladbach, Stadt", "Nordrhein-Westfalen", "", "D", "MGH",
			"Bad Mergentheim, Kreis (TBB)", "Baden-Württemberg", "X", "D",
			"MGN", "Meiningen, Kreis (SM)", "Thüringen", "X", "D", "MH",
			"Mülheim a. d. Ruhr, Stadt", "Nordrhein-Westfalen", "", "D", "MHL",
			"Mühlhausen, Kreis (UH)", "Thüringen", "X", "D", "MI",
			"Minden-Lübbecke in Minden, Kreis", "Nordrhein-Westfalen", "", "D",
			"MIL", "Miltenberg, Kreis", "Bayern", "", "D", "MK",
			"Märkischer Kreis in Lüdenscheid, Kreis", "Nordrhein-Westfalen",
			"", "D", "MKK", "Main-Kinzig-Kreis", "Hessen", "", "D", "MSH",
			"Landkreis Mansfeld-Südharz", "Sachsen-Anhalt", "", "D", "ML",
			"Mansfelder Land in Eisleben, Kreis", "Sachsen-Anhalt", "X", "D",
			"MM", "Memmingen, Stadt", "Bayern", "", "D", "MN",
			"Unterallgäu in Mindelheim, Kreis", "Bayern", "", "D", "MO",
			"Moers, Kreis (WES)", "Nordrhein-Westfalen", "X", "D", "MOD",
			"Ostallgäu in Marktoberdorf, Kreis (OAL)", "Bayern", "X", "D",
			"MOL", "Märkisch-Oderland in Bad Freienwalde, Kreis",
			"Brandenburg", "", "D", "MON", "Monschau, Kreis (AC)",
			"Nordrhein-Westfalen", "X", "D", "MOS",
			"Neckar-Odenwald-Kreis in Mosbach, Kreis", "Baden-Württemberg", "",
			"D", "MQ", "Merseburg-Querfurt in Merseburg, Kreis",
			"Sachsen-Anhalt", "X", "D", "MR",
			"Marburg-Biedenkopf in Marburg/Lahn, Kreis", "Hessen", "", "D",
			"MS", "Münster, Stadt", "Nordrhein-Westfalen", "", "D", "MSP",
			"Main-Spessart in Karlstadt, Kreis", "Bayern", "", "D", "MST",
			"Mecklenburg-Strelitz in Neustrelitz, Kreis",
			"Mecklenburg-Vorpommern", "", "D", "MT",
			"Westerwald in Montabaur, Kreis (WW)", "Rheinland-Pfalz", "X", "D",
			"MTK", "Main-Taunus-Kreis in Hofheim am Taunus, Kreis", "Hessen",
			"", "D", "MTL", "Muldentalkreis in Grimma, Kreis", "Sachsen", "",
			"D", "MÜ", "Mühldorf a. Inn, Kreis", "Bayern", "", "D", "MÜB",
			"Münchberg, Kreis (HO)", "Bayern", "X", "D", "MÜL",
			"Müllheim Baden, Kreis (FR)", "Baden-Württemberg", "X", "D", "MÜN",
			"Münsingen/Württemberg, Kreis (RT)", "Baden-Württemberg", "X", "D",
			"MÜR", "Müritz in Waren, Kreis", "Mecklenburg-Vorpommern", "", "D",
			"MW", "Mittweida, Kreis", "Sachsen", "", "D", "MY",
			"Mayen, Kreis (MYK)", "Rheinland-Pfalz", "X", "D", "MYK",
			"Mayen-Koblenz in Koblenz, Kreis und Andernach, Stadt",
			"Rheinland-Pfalz", "", "D", "MZ",
			"Mainz, Stadt, Mainz-Bingen in Bingen, Kreis", "Rheinland-Pfalz",
			"", "D", "MZG", "Merzig-Wadern in Merzig/Saar, Kreis", "Saarland",
			"", "D", "N", "Nürnberg, Stadt", "Bayern", "", "D", "NAB",
			"Nabburg, Kreis (SAD)", "Bayern", "X", "D", "NAI",
			"Naila, Kreis (HO)", "Bayern", "X", "D", "NAU",
			"Nauen, Kreis (HVL)", "Brandenburg", "X", "D", "NB",
			"Neubrandenburg, Stadt", "Mecklenburg-Vorpommern", "", "D", "ND",
			"Neuburg-Schrobenhausen in Neuburg a. d. Donau, Kreis", "Bayern",
			"", "D", "NDH", "Nordhausen, Kreis", "Thüringen", "", "D", "NE",
			"Neuss, Kreis", "Nordrhein-Westfalen", "", "D", "NEA",
			"Neustadt a. d. Aisch - Bad Windsheim", "Bayern", "", "D", "NEB",
			"Nebra, Kreis (BLK)", "Sachsen-Anhalt", "X", "D", "NEC",
			"Neustadt b. Coburg, Stadt (CO)", "Bayern", "X", "D", "NEN",
			"Neunburg vorm Wald, Kreis (SAD)", "Bayern", "X", "D", "NES",
			"Rhön-Grabfeld in Bad Neustadt a. d. Saale, Kreis", "Bayern", "",
			"D", "NEU", "Hochschwarzwald in Titisee-Neustadt, Kreis (FR)",
			"Baden-Württemberg", "X", "D", "NEW",
			"Neustadt a. d. Waldnaab, Kreis", "Bayern", "", "D", "NF",
			"Nordfriesland in Husum, Kreis", "Schleswig-Holstein", "", "D",
			"NH", "Neuhaus, Kreis (SON)", "Thüringen", "X", "D", "NI",
			"Nienburg/Weser, Kreis", "Niedersachsen", "", "D", "NIB",
			"Süd Tondern in Niebüll/Schleswig, Kreis (NF)",
			"Schleswig-Holstein", "X", "D", "NK", "Neunkirchen/Saar, Kreis",
			"Saarland", "", "D", "NM", "Neumarkt i. d. OPf., Kreis", "Bayern",
			"", "D", "NMB", "Naumburg, Kreis (BLK)", "Sachsen-Anhalt", "X",
			"D", "NMS", "Neumünster, Stadt", "Schleswig-Holstein", "", "D",
			"NÖ", "Nördlingen, Stadt und Kreis (DON)", "Bayern", "X", "D",
			"NOH", "Grafschaft Bentheim in Nordhorn, Kreis", "Niedersachsen",
			"", "D", "NOL",
			"Niederschlesischer Oberlausitzkreis in Niesky, Kreis", "Sachsen",
			"", "D", "NOM", "Northeim, Kreis", "Niedersachsen", "", "D", "NOR",
			"Norden, Kreis (AUR)", "Niedersachsen", "X", "D", "NP",
			"Neuruppin, Kreis (OPR)", "Brandenburg", "X", "D", "NR",
			"Neuwied/Rhein, Stadt und Kreis", "Rheinland-Pfalz", "", "D",
			"NRÜ", "Neustadt am Rübenberge, Kreis (H)", "Niedersachsen", "X",
			"D", "NT", "Nürtingen, Kreis (ES)", "Baden-Württemberg", "X", "D",
			"NU", "Neu-Ulm, Kreis", "Bayern", "", "D", "NVP",
			"Nordvorpommern in Grimmen, Kreis", "Mecklenburg-Vorpommern", "",
			"D", "NW", "Neustadt/Weinstraße, Stadt", "Rheinland-Pfalz", "",
			"D", "NWM", "Nordwestmecklenburg in Grevesmühlen, Kreis",
			"Mecklenburg-Vorpommern", "", "D", "NY", "Niesky, Kreis (NOL)",
			"Sachsen", "X", "D", "NZ", "Neustrelitz, Kreis (MST)",
			"Mecklenburg-Vorpommern", "X", "D", "OA",
			"Oberallgäu in Sonthofen, Kreis", "Bayern", "", "D", "OAL",
			"Ostallgäu in Marktoberdorf, Kreis", "Bayern", "", "D", "OB",
			"Oberhausen, Stadt", "Nordrhein-Westfalen", "", "D", "OBB",
			"Obernburg a. Main, Kreis (MIL)", "Bayern", "X", "D", "OBG",
			"Osterburg, Kreis (SDL)", "Sachsen-Anhalt", "X", "D", "OC",
			"Bördekreis in Oschersleben, Kreis (BÖ)", "Sachsen-Anhalt", "X",
			"D", "OCH", "Ochsenfurt, Kreis (WÜ)", "Bayern", "X", "D", "OD",
			"Stormarn in Bad Oldesloe, Kreis", "Schleswig-Holstein", "", "D",
			"OE", "Olpe, Kreis", "Nordrhein-Westfalen", "", "D", "OF",
			"Offenbach/Main, Stadt und Kreis", "Hessen", "", "D", "OG",
			"Ortenaukreis in Offenburg, Kreis", "Baden-Württemberg", "", "D",
			"OH", "Ostholstein in Eutin, Kreis", "Schleswig-Holstein", "", "D",
			"OHA", "Osterode Harz, Kreis", "Niedersachsen", "", "D", "ÖHR",
			"Öhringen, Kreis (KÜN)", "Baden-Württemberg", "X", "D", "OHV",
			"Oberhavel in Oranienburg, Kreis", "Brandenburg", "", "D", "OHZ",
			"Osterholz in Osterholz-Scharmbeck, Kreis", "Niedersachsen", "",
			"D", "OK", "Ohrekreis in Haldensleben, Kreis", "Sachsen-Anhalt",
			"X", "D", "OL", "Oldenburg/Oldenburg, Stadt", "Niedersachsen", "",
			"D", "OLD", "Oldenburg/Holstein, Kreis (OH)", "Schleswig-Holstein",
			"X", "D", "OP", "Rhein-Wupperkreis in Opladen, Kreis (GL)",
			"Nordrhein-Westfalen", "X", "D", "OPR",
			"Ostprignitz-Ruppin in Neuruppin, Kreis", "Brandenburg", "", "D",
			"OR", "Oranienburg, Kreis (OHV)", "Brandenburg", "X", "D", "OS",
			"Osnabrück, Stadt und Kreis", "Niedersachsen", "", "D", "OSL",
			"Oberspreewald-Lausitz in Senftenberg, Kreis", "Brandenburg", "",
			"D", "OTT", "Land Hadeln in Otterndorf, Kreis (CUX)",
			"Niedersachsen", "X", "D", "OTW", "Ottweiler, Kreis (NK)",
			"Saarland", "X", "D", "OVI", "Overviechtach, Kreis (SAD)",
			"Bayern", "X", "D", "OVL",
			"Obervogtland, Kreis in Klingenthal und Oelsnitz (V)", "Sachsen",
			"X", "D", "OVP", "Ostvorpommern in Anklam, Kreis",
			"Mecklenburg-Vorpommern", "", "D", "OZ", "Oschatz, Kreis (TO)",
			"Sachsen", "X", "D", "P", "Potsdam, Stadt", "Brandenburg", "", "D",
			"PA", "Passau, Stadt und Kreis", "Bayern", "", "D", "PAF",
			"Pfaffenhofen a. d. Ilm, Kreis", "Bayern", "", "D", "PAN",
			"Rottal-Inn in Pfarrkirchen, Kreis", "Bayern", "", "D", "PAR",
			"Parsberg, Kreis (NM)", "Bayern", "X", "D", "PB",
			"Paderborn, Kreis", "Nordrhein-Westfalen", "", "D", "PCH",
			"Parchim, Kreis", "Mecklenburg-Vorpommern", "", "D", "PE",
			"Peine, Kreis", "Niedersachsen", "", "D", "PEG",
			"Pegnitz, Kreis (BT)", "Bayern", "X", "D", "PER",
			"Perleberg, Kreis (PR)", "Brandenburg", "X", "D", "PF",
			"Pforzheim, Stadt", "Baden-Württemberg", "", "D", "PI",
			"Pinneberg, Kreis", "Schleswig-Holstein", "", "D", "PIR",
			"Sächsische Schweiz in Pirna, Kreis", "Sachsen", "", "D", "PK",
			"Pritzwalk, Kreis (PR)", "Brandenburg", "X", "D", "PL",
			"Plauen, Stadt", "Sachsen", "", "D", "PLÖ", "Plön/Holstein, Kreis",
			"Schleswig-Holstein", "", "D", "PM",
			"Potsdam-Mittelmark in Belzig, Kreis", "Brandenburg", "", "D",
			"PN", "Pößneck, Kreis (SOK)", "Thüringen", "X", "D", "PR",
			"Prignitz in Perleberg, Kreis", "Brandenburg", "", "D", "PRÜ",
			"Prüm Eifel, Kreis (BIT)", "Rheinland-Pfalz", "X", "D", "PS",
			"Pirmasens, Stadt und Kreis", "Rheinland-Pfalz", "", "D", "PW",
			"Pasewalk, Kreis (UER)", "Mecklenburg-Vorpommern", "X", "D", "PZ",
			"Prenzlau, Kreis (UM)", "Brandenburg", "X", "D", "QFT",
			"Querfurt, Kreis (MQ)", "Sachsen-Anhalt", "X", "D", "QLB",
			"Quedlinburg, Kreis", "Sachsen-Anhalt", "X", "D", "R",
			"Regensburg, Stadt und Kreis", "Bayern", "", "D", "RA",
			"Rastatt, Kreis", "Baden-Württemberg", "", "D", "RC",
			"Reichenbach, Kreis (V)", "Sachsen", "X", "D", "RD",
			"Rendsburg-Eckernförde in Rendsburg, Kreis", "Schleswig-Holstein",
			"", "D", "RDG", "Ribnitz-Damgarten, Kreis (NVP)",
			"Mecklenburg-Vorpommern", "X", "D", "RE",
			"Recklinghausen in Marl, Kreis", "Nordrhein-Westfalen", "", "D",
			"REG", "Regen, Kreis", "Bayern", "", "D", "REH",
			"Rehau, Kreis (HO)", "Bayern", "X", "D", "REI",
			"Berchtesgadener Land in Bad Reichenhall, Kreis (BGL)", "Bayern",
			"X", "D", "RG", "Riesa-Großenhain in Großenhain, Kreis", "Sachsen",
			"", "D", "RH", "Roth, Kreis", "Bayern", "", "D", "RI",
			"Grafschaft Schaumburg in Rinteln, Kreis (SHG)", "Niedersachsen",
			"X", "D", "RID", "Riedenburg, Kreis (KEH)", "Bayern", "X", "D",
			"RIE", "Riesa, Kreis (RG)", "Sachsen", "X", "D", "RL",
			"Rochlitz, Kreis (MW)", "Sachsen", "X", "D", "RM",
			"Röbel/Müritz, Kreis (MÜR)", "Mecklenburg-Vorpommern", "X", "D",
			"RN", "Rathenow, Kreis (HVL)", "Brandenburg", "X", "D", "RO",
			"Rosenheim, Stadt und Kreis", "Bayern", "", "D", "ROD",
			"Roding, Kreis (CHA)", "Bayern", "X", "D", "ROF",
			"Rotenburg/Fulda, Kreis (HEF)", "Hessen", "X", "D", "ROK",
			"Rockenhausen, Kreis (KIB)", "Rheinland-Pfalz", "X", "D", "ROL",
			"Rottenburg a. d. Laaber, Kreis (LA)", "Bayern", "X", "D", "ROS",
			"Rostock, Kreis (DBR)", "Mecklenburg-Vorpommern", "X", "D", "ROT",
			"Rothenburg ob der Tauber, Stadt und Kreis (AN)", "Bayern", "X",
			"D", "ROW", "Rotenburg (Wümme), Kreis", "Niedersachsen", "", "D",
			"RS", "Remscheid, Stadt", "Nordrhein-Westfalen", "", "D", "RSL",
			"Roßlau, Kreis (AZE)", "Sachsen-Anhalt", "X", "D", "RT",
			"Reutlingen, Kreis", "Baden-Württemberg", "", "D", "RU",
			"Rudolstadt, Kreis (SLF)", "Thüringen", "X", "D", "RÜD",
			"Rheingau-Taunus-Kreis in Bad Schwalbach, Kreis", "Hessen", "",
			"D", "RÜG", "Rügen in Bergen, Kreis", "Mecklenburg-Vorpommern", "",
			"D", "RP", "Rhein-Pfalz-Kreis", "Rheinland-Pfalz", "", "D", "RV",
			"Ravensburg, Kreis", "Baden-Württemberg", "", "D", "RW",
			"Rottweil, Kreis", "Baden-Württemberg", "", "D", "RY",
			"Rheydt, Stadt (MG)", "Nordrhein-Westfalen", "X", "D", "RZ",
			"Herzogtum Lauenburg in Ratzeburg, Kreis", "Schleswig-Holstein",
			"", "D", "S", "Stuttgart, Stadt", "Baden-Württemberg", "", "D",
			"SAB", "Saarburg Bz. Trier, Kreis (TR)", "Rheinland-Pfalz", "X",
			"D", "SAD", "Schwandorf, Kreis", "Bayern", "", "D", "SÄK",
			"Säckingen, Kreis (WT)", "Baden-Württemberg", "X", "D", "SAN",
			"Stadtsteinach, Kreis (KU)", "Bayern", "X", "D", "SAW",
			"Altmarkkreis Salzwedel in Salzwedel, Kreis", "Sachsen-Anhalt",
			"X", "D", "SB", "Saarbrücken, Stadt und Stadtverband", "Saarland",
			"", "D", "SBG", "Strasburg, Kreis (UER)", "Mecklenburg-Vorpommern",
			"X", "D", "SBK", "Schönebeck, Kreis", "Sachsen-Anhalt", "X", "D",
			"SC", "Schwabach, Stadt", "Bayern", "", "D", "SCZ",
			"Schleiz, Kreis (SOK)", "Thüringen", "X", "D", "SDH",
			"Sondershausen, Kreis (KYF)", "Thüringen", "X", "D", "SDL",
			"Stendal, Kreis", "Sachsen-Anhalt", "X", "D", "SDT",
			"Schwedt/Oder, Kreis (UM)", "Brandenburg", "X", "D", "SE",
			"Segeberg in Bad Segeberg, Kreis", "Schleswig-Holstein", "", "D",
			"SEB", "Sebnitz, Kreis (PIR)", "Sachsen", "X", "D", "SEE",
			"Seelow, Kreis (MOL)", "Brandenburg", "X", "D", "SEF",
			"Scheinfeld, Kreis (NEA)", "Bayern", "X", "D", "SEL",
			"Selb, Stadt (WUN)", "Bayern", "X", "D", "SF",
			"Oberallgäu in Sonthofen, Kreis (OA)", "Bayern", "X", "D", "SFA",
			"Soltau-Fallingbostel in Fallingbostel, Kreis(HK)", "Niedersachsen",
			"X", "D", "SFB", "Senftenberg, Kreis (OSL)", "Brandenburg", "X",
			"D", "SFT", "Staßfurt, Kreis (ASL)", "Sachsen-Anhalt", "X", "D",
			"SG", "Solingen, Stadt", "Nordrhein-Westfalen", "", "D", "SGH",
			"Sangerhausen, Kreis", "Sachsen-Anhalt", "X", "D", "SHA",
			"Schwäbisch Hall, Kreis", "Baden-Württemberg", "", "D", "SHG",
			"Schaumburg in Stadthagen, Kreis", "Niedersachsen", "", "D", "SHK",
			"Saale-Holzlandkreis in Eisenberg, Kreis", "Thüringen", "", "D",
			"SHL", "Suhl, Stadt", "Thüringen", "", "D", "SI",
			"Siegen-Wittgenstein in Siegen, Kreis", "Nordrhein-Westfalen", "",
			"D", "SIG", "Sigmaringen, Kreis", "Baden-Württemberg", "", "D",
			"SIM", "Rhein-Hunsrück-Kreis in Simmern, Kreis", "Rheinland-Pfalz",
			"", "D", "SK", "Saalkreis in Halle, Kreis", "Sachsen-Anhalt", "X",
			"D", "SL", "Schleswig-Flensburg in Schleswig, Kreis",
			"Schleswig-Holstein", "", "D", "SLK", "Salzlandkreis",
			"Sachsen-Anhalt", "", "D", "SLE", "Schleiden, Kreis (EU)",
			"Nordrhein-Westfalen", "X", "D", "SLF",
			"Saalfeld-Rudolstadt in Saalfeld, Kreis", "Thüringen", "", "D",
			"SLG", "Saulgau/Württemberg, Kreis (SIG)", "Baden-Württemberg",
			"X", "D", "SLN", "Schmölln, Kreis (ABG)", "Thüringen", "X", "D",
			"SLS", "Saarlouis, Kreis", "Saarland", "", "D", "SLÜ",
			"Schlüchtern, Kreis (HU)", "Hessen", "X", "D", "SLZ",
			"Bad Salzungen, Kreis (WAK)", "Thüringen", "X", "D", "SM",
			"Schmalkalden-Meiningen in Meiningen, Kreis", "Thüringen", "", "D",
			"SMÜ", "Schwabmünchen, Kreis (A)", "Bayern", "X", "D", "SN",
			"Schwerin, Stadt", "Mecklenburg-Vorpommern", "", "D", "SNH",
			"Sinsheim/Elsenz, Kreis (HD)", "Baden-Württemberg", "X", "D", "SO",
			"Soest, Kreis", "Nordrhein-Westfalen", "", "D", "SOB",
			"Schrobenhausen, Kreis (ND)", "Bayern", "X", "D", "SOG",
			"Schongau, Kreis (WM)", "Bayern", "X", "D", "SOK",
			"Saale-Orla-Kreis in Oberböhmsdorf, Kreis", "Thüringen", "", "D",
			"SOL", "Soltau, Kreis (SFA)", "Niedersachsen", "X", "D", "SÖM",
			"Sömmerda, Kreis", "Thüringen", "", "D", "SON", "Sonneberg, Kreis",
			"Thüringen", "", "D", "SP", "Speyer, Stadt", "Rheinland-Pfalz", "",
			"D", "SPB", "Spremberg, Kreis (SPN)", "Brandenburg", "X", "D",
			"SPN", "Spree-Neiße in Forst, Kreis", "Brandenburg", "", "D",
			"SPR", "Springe, Kreis (H)", "Niedersachsen", "X", "D", "SR",
			"Straubing, Stadt", "Bayern", "", "D", "SRB",
			"Strausberg, Kreis (MOL)", "Brandenburg", "X", "D", "SRO",
			"Stadtroda, Kreis (SHK)", "Thüringen", "X", "D", "ST",
			"Steinfurt, Kreis", "Nordrhein-Westfalen", "", "D", "STA",
			"Starnberg, Kreis", "Bayern", "", "D", "STB",
			"Sternberg, Kreis (PCH)", "Mecklenburg-Vorpommern", "X", "D",
			"STD", "Stade, Kreis", "Niedersachsen", "", "D", "STE",
			"Staffelstein, Kreis (LIF)", "Bayern", "X", "D", "STH",
			"Schaumburg-Lippe in Stadthagen, Kreis (SHG)", "Niedersachsen",
			"X", "D", "STL", "Stollberg, Kreis", "Sachsen", "", "D", "STO",
			"Stockach/Baden, Kreis (KN)", "Baden-Württemberg", "X", "D", "SU",
			"Rhein-Sieg-Kreis in Siegburg, Kreis", "Nordrhein-Westfalen", "",
			"D", "SUL", "Sulzbach-Rosenberg, Kreis (AM)", "Bayern", "X", "D",
			"SÜW", "Südliche Weinstraße in Landau, Kreis", "Rheinland-Pfalz",
			"", "D", "SW", "Schweinfurt, Stadt und Kreis", "Bayern", "", "D",
			"SWA", "Rheingau-Taunus-Kreis in Bad Schwalbach (RÜD)", "Hessen",
			"X", "D", "SY", "Grafschaft Hoya in Syke, Kreis (DH)",
			"Niedersachsen", "X", "D", "SZ", "Salzgitter, Stadt",
			"Niedersachsen", "", "D", "SZB", "Schwarzenberg, Kreis (ASZ)",
			"Sachsen", "X", "D", "TBB",
			"Main-Tauber-Kreis in Tauberbischofsheim, Kreis",
			"Baden-Württemberg", "", "D", "TE", "Tecklenburg, Kreis (ST)",
			"Nordrhein-Westfalen", "X", "D", "TET", "Teterow, Kreis (GÜ)",
			"Mecklenburg-Vorpommern", "X", "D", "TF",
			"Teltow-Fläming in Zossen, Kreis", "Brandenburg", "", "D", "TG",
			"Torgau, Kreis (TO)", "Sachsen", "X", "D", "THW",
			"Bundesanstalt Technisches Hilfswerk", "", "", "D", "TIR",
			"Tirschenreuth, Kreis", "Bayern", "", "D", "TO",
			"Torgau-Oschatz in Torgau, Kreis", "Sachsen", "", "D", "TÖL",
			"Bad Tölz-Wolfratshausen in Bad Tölz, Kreis", "Bayern", "", "D",
			"TÖN", "Eiderstedt in Tönning/Nordseebad, Kreis (NF)",
			"Schleswig-Holstein", "X", "D", "TP", "Templin, Kreis (UM)",
			"Brandenburg", "X", "D", "TR", "Trier, Stadt", "Rheinland-Pfalz",
			"", "D", "TS", "Traunstein, Kreis", "Bayern", "", "D", "TT",
			"Tettnang/Württemberg, Kreis (FN)", "Baden-Württemberg", "X", "D",
			"TÜ", "Tübingen, Kreis", "Baden-Württemberg", "", "D", "TUT",
			"Tuttlingen, Kreis", "Baden-Württemberg", "", "D", "ÜB",
			"Überlingen/Bodensee, Kreis (FN)", "Baden-Württemberg", "X", "D",
			"UE", "Uelzen, Kreis", "Niedersachsen", "", "D", "UEM",
			"Ueckermünde, Kreis (UER)", "Mecklenburg-Vorpommern", "X", "D",
			"UER", "Uecker-Randow in Pasewalk, Kreis",
			"Mecklenburg-Vorpommern", "", "D", "UFF", "Uffenheim, Kreis (NEA)",
			"Bayern", "X", "D", "UH",
			"Unstrut-Hainich-Kreis in Mühlhausen, Kreis", "Thüringen", "", "D",
			"UL", "Ulm/Donau, Stadt", "Baden-Württemberg", "", "D", "UM",
			"Uckermark in Prenzlau, Kreis", "Brandenburg", "", "D", "UN",
			"Unna, Kreis", "Nordrhein-Westfalen", "", "D", "USI",
			"Usingen/Taunus, Kreis (HG)", "Hessen", "X", "D", "V",
			"Vogtlandkreis in Plauen, Kreis", "Sachsen", "", "D", "VAI",
			"Vaihingen/Enz, Kreis (LB)", "Baden-Württemberg", "X", "D", "VB",
			"Vogelsbergkreis in Lauterbach/Hessen, Kreis", "Hessen", "", "D",
			"VEC", "Vechta, Kreis", "Niedersachsen", "", "D", "VER",
			"Verden in Verden/Aller, Kreis", "Niedersachsen", "", "D", "VIB",
			"Vilsbiburg, Kreis (LA)", "Bayern", "X", "D", "VIE",
			"Viersen, Kreis", "Nordrhein-Westfalen", "", "D", "VIT",
			"Viechtach, Kreis (REG)", "Bayern", "X", "D", "VK",
			"Völklingen, Stadt", "Saarland", "", "D", "VL",
			"Villingen/Schwarzwald, Kreis (VS)", "Baden-Württemberg", "X", "D",
			"VOF", "Vilshofen, Kreis (PA)", "Bayern", "X", "D", "VOH",
			"Vohenstrauß, Kreis (NEW)", "Bayern", "X", "D", "VS",
			"Schwarzwald-Baar-Kreis in Villingen-Schwenningen",
			"Baden-Württemberg", "", "D", "W", "Wuppertal, Stadt",
			"Nordrhein-Westfalen", "", "D", "WA",
			"Waldeck in Korbach, Kreis (KB)", "Hessen", "X", "D", "WAF",
			"Warendorf, Kreis", "Nordrhein-Westfalen", "", "D", "WAK",
			"Wartburgkreis in Bad Salzungen, Kreis", "Thüringen", "", "D",
			"WAN", "Wanne-Eickel, Stadt (HER)", "Nordrhein-Westfalen", "X",
			"D", "WAR", "Warburg, Kreis (HX)", "Nordrhein-Westfalen", "X", "D",
			"WAT", "Wattenscheid, Stadt (BO)", "Nordrhein-Westfalen", "X", "D",
			"WB", "Wittenberg, Kreis", "Sachsen-Anhalt", "X", "D", "WBS",
			"Worbis, Kreis (EIC)", "Thüringen", "X", "D", "WD",
			"Wiedenbrück, Kreis (GT)", "Nordrhein-Westfalen", "X", "D", "WDA",
			"Werdau, Kreis (Z)", "Sachsen", "X", "D", "WE", "Weimar, Stadt",
			"Thüringen", "", "D", "WEB",
			"Oberwesterwaldkreis in Westerburg, (WW)", "Rheinland-Pfalz", "X",
			"D", "WEG", "Wegscheid, Kreis (PA)", "Bayern", "X", "D", "WEL",
			"Oberlahnkreis in Weilburg, Kreis (LM)", "Hessen", "X", "D", "WEM",
			"Wesermünde in Bremerhaven, Kreis (CUX)", "Niedersachsen", "X",
			"D", "WEN", "Weiden i. d. OPf., Stadt", "Bayern", "", "D", "WER",
			"Wertingen, Kreis (DLG)", "Bayern", "X", "D", "WES",
			"Wesel, Kreis", "Nordrhein-Westfalen", "", "D", "WF",
			"Wolfenbüttel, Kreis", "Niedersachsen", "", "D", "WG",
			"Wangen/Allgäu, Kreis (RV)", "Baden-Württemberg", "X", "D", "WHV",
			"Wilhelmshaven, Stadt", "Niedersachsen", "", "D", "WI",
			"Wiesbaden, Stadt", "Hessen", "", "D", "WIL",
			"Bernkastel-Wittlich in Wittlich, Kreis", "Rheinland-Pfalz", "",
			"D", "WIS", "Wismar, Kreis (NWM)", "Mecklenburg-Vorpommern", "X",
			"D", "WIT", "Witten, Stadt (EN)", "Nordrhein-Westfalen", "X", "D",
			"WIZ", "Witzenhausen, Kreis (ESW)", "Hessen", "X", "D", "WK",
			"Wittstock, Kreis (OPR)", "Brandenburg", "X", "D", "WL",
			"Harburg in Winsen/Luhe, Kreis", "Niedersachsen", "", "D", "WLG",
			"Wolgast, Kreis (OVP)", "Mecklenburg-Vorpommern", "X", "D", "WM",
			"Weilheim-Schongau in Weilheim i. OB., Kreis", "Bayern", "", "D",
			"WMS", "Wolmirstedt, Kreis (OK)", "Sachsen-Anhalt", "X", "D", "WN",
			"Rems-Murr-Kreis in Waiblingen, Kreis", "Baden-Württemberg", "",
			"D", "WND", "St. Wendel, Kreis", "Saarland", "", "D", "WO",
			"Worms, Stadt", "Rheinland-Pfalz", "", "D", "WOB",
			"Wolfsburg, Stadt", "Niedersachsen", "", "D", "WOH",
			"Wolfhagen Bz. Kassel, Kreis (KS)", "Hessen", "X", "D", "WOL",
			"Wolfach, Kreis (OG)", "Baden-Württemberg", "X", "D", "WOR",
			"Wolfratshausen, Kreis (TÖL)", "Bayern", "X", "D", "WOS",
			"Wolfstein, Kreis (FRG)", "Bayern", "X", "D", "WR",
			"Wernigerode, Kreis", "Sachsen-Anhalt", "X", "D", "WRN",
			"Waren, Kreis (MÜR)", "Mecklenburg-Vorpommern", "X", "D", "WS",
			"Wasserburg a. Inn, Kreis (RO)", "Bayern", "X", "D", "WSF",
			"Weißenfels, Kreis", "Sachsen-Anhalt", "X", "D", "WST",
			"Ammerland in Westerstede, Kreis", "Niedersachsen", "", "D", "WSW",
			"Weißwasser, Kreis (NOL)", "Sachsen", "X", "D", "WT",
			"Waldshut in Waldshut-Tiengen, Kreis", "Baden-Württemberg", "",
			"D", "WTL", "Wittlage, Kreis (OS)", "Niedersachsen", "X", "D",
			"WTM", "Wittmund, Kreis", "Niedersachsen", "", "D", "WÜ",
			"Würzburg, Stadt und Kreis", "Bayern", "", "D", "WUG",
			"Weißenburg-Gunzenhausen in Weißenburg, Kreis", "Bayern", "", "D",
			"WÜM", "Waldmünchen, Kreis (CHA)", "Bayern", "X", "D", "WUN",
			"Wunsiedel i. Fichtelgebirge, Kreis", "Bayern", "", "D", "WUR",
			"Wurzen, Kreis (MTL)", "Sachsen", "X", "D", "WW",
			"Westerwald in Montabaur, Kreis", "Rheinland-Pfalz", "", "D", "WZ",
			"Wetzlar, Kreis (LDK)", "Hessen", "X", "D", "WZL",
			"Wanzleben, Kreis (BÖ)", "Sachsen-Anhalt", "X", "D", "Z",
			"Zwickau, Stadt", "Sachsen", "", "D", "ZE", "Zerbst, Kreis (AZE)",
			"Sachsen-Anhalt", "X", "D", "ZEL", "Zell/Mosel, Kreis (COC)",
			"Rheinland-Pfalz", "X", "D", "ZI", "Löbau-Zittau in Zittau, Kreis",
			"Sachsen", "", "D", "ZIG", "Ziegenhain Bz. Kassel, Kreis (HR)",
			"Hessen", "X", "D", "ZP", "Zschopau, Kreis (MEK)", "Sachsen", "X",
			"D", "ZR", "Zeulenroda, Kreis (GRZ)", "Thüringen", "X", "D", "ZS",
			"Zossen, Kreis (TF)", "Brandenburg", "X", "D", "ZW",
			"Zweibrücken, Stadt", "Rheinland-Pfalz", "", "D", "ZZ",
			"Zeitz, Kreis (BLK)", "Sachsen-Anhalt", "X", "IT", "AG",
			"Agrigento", "", "", "IT", "AL", "Alessandria", "", "", "IT", "AM",
			"Aeronautica Militare, Italienische Luftwaffe", "", "", "IT", "AN",
			"Ancona", "", "", "IT", "AO", "Valle d'Aosta", "", "", "IT", "AP",
			"Ascoli Piceno", "", "", "IT", "AQ", "L'Aquila", "", "", "IT",
			"AR", "Arezzo", "", "", "IT", "AT", "Asti", "", "", "IT", "AU",
			"Apuania", "", "", "IT", "AV", "Avellino", "", "", "IT", "BA",
			"Bari", "", "", "IT", "BG", "Bergamo", "", "", "IT", "BI",
			"Biella", "", "", "IT", "BL", "Belluno", "", "", "IT", "BN",
			"Benevento", "", "", "IT", "BO", "Bologna", "", "", "IT", "BR",
			"Brindisi", "", "", "IT", "BS", "Brescia", "", "", "IT", "BT",
			"Barletta Andria Trani", "", "", "IT", "BZ", "Bolzano", "", "",
			"IT", "CA", "Cagliari", "", "", "IT", "CB", "Campobasso", "", "",
			"IT", "CC", "Carabinieri (Pluralabkürzung Carabinieri)", "", "",
			"IT", "CC", "Corpo Consulare, Konsularisches Corps", "", "", "IT",
			"CD", "Corpo Diplomatico, Diplomatisches Corps", "", "", "IT",
			"CE", "Caserta", "", "", "IT", "CFS",
			"Corpo Forestale dello Stato, Forstbehörden", "", "", "IT", "CG",
			"Castrogiovanni", "", "", "IT", "CH", "Chieti", "", "", "IT", "CI",
			"Carbonia Iglesias", "", "", "IT", "CL", "Caltanissetta", "", "",
			"IT", "CN", "Cuneo", "", "", "IT", "CO", "Como", "", "", "IT",
			"CP", "Capitaneria di Porto, Küstenwache", "", "", "IT", "CR",
			"Cremona", "", "", "IT", "CRI",
			"Croce Rossa Italiana, Italienisches Rotes Kreuz", "", "", "IT",
			"CS", "Cosenza", "", "", "IT", "CT", "Catania", "", "", "IT", "CU",
			"Cuneo", "", "", "IT", "CZ", "Catanzaro", "", "", "IT", "EE",
			"Escursioni Esteri, Ausländer ohne Wohnsitz in Italien", "", "",
			"IT", "EI", "Esercito Italiano, Italienisches Heer", "", "", "IT",
			"EN", "Enna", "", "", "IT", "FC", "Forlì-Cesena", "", "", "IT",
			"FE", "Ferrara", "", "", "IT", "FG", "Foggia", "", "", "IT", "FI",
			"Firenze", "", "", "IT", "FM", "Fermo", "", "", "IT", "FM",
			"Fiume", "", "", "IT", "FO", "Forlì Cesena", "", "", "IT", "FR",
			"Frosinone", "", "", "IT", "FU", "Fiume", "", "", "IT", "GdiF",
			"Guardia di Finanza, FinanzZollPolizei", "", "", "IT", "GE",
			"Genova", "", "", "IT", "GI", "Girgenti", "", "", "IT", "GO",
			"Gorizia", "", "", "IT", "GR", "Grosseto", "", "", "IT", "IM",
			"Imperia", "", "", "IT", "IS", "Isernia", "", "", "IT", "KR",
			"Crotone", "", "", "IT", "LC", "Lecco", "", "", "IT", "LE",
			"Lecce", "", "", "IT", "LI", "Livorno", "", "", "IT", "LO", "Lodi",
			"", "", "IT", "LT", "Latina", "", "", "IT", "LU", "Lucca", "", "",
			"IT", "MB", "Monza e Brianza", "", "", "IT", "MC", "Macerata", "",
			"", "IT", "MD", "Medio Campidano", "", "", "IT", "ME", "Messina",
			"", "", "IT", "MI", "Milano", "", "", "IT", "MM",
			"Marina Militare, Italienische Marine", "", "", "IT", "MN",
			"Mantova", "", "", "IT", "MO", "Modena", "", "", "IT", "MS",
			"Massa Carrara", "", "", "IT", "MT", "Matera", "", "", "IT", "NA",
			"Napoli", "", "", "IT", "NO", "Novara", "", "", "IT", "NU",
			"Nuoro", "", "", "IT", "OG", "Ogliastra", "", "", "IT", "OR",
			"Oristano", "", "", "IT", "OT", "Olbia Tempio", "", "", "IT", "PA",
			"Palermo", "", "", "IT", "PC", "Piacenza", "", "", "IT", "PC",
			"Protezione Civile, Zivilschutz", "", "", "IT", "PD", "Padova", "",
			"", "IT", "PE", "Pescara", "", "", "IT", "PG", "Perugia", "", "",
			"IT", "PI", "Pisa", "", "", "IT", "PN", "Pordenone", "", "", "IT",
			"PO", "Prato", "", "", "IT", "PO\nLI\nZIA", "Polizia, Polizei", "", "",
			"IT", "PO\nLI\nZIA\nPEN\nITE\nNZI\nARI\nA",
			"Polizia Penitenziaria, Justizwache", "", "", "IT", "PR", "Parma",
			"", "", "IT", "PS", "Pesaro Urbino", "", "", "IT", "PT", "Pistoia",
			"", "", "IT", "PU", "Pesaro e Urbino", "", "", "IT", "PU",
			"Perugia", "", "", "IT", "PV", "Pavia", "", "", "IT", "PZ",
			"Potenza", "", "", "IT", "RA", "Ravenna", "", "", "IT", "RC",
			"Reggio di Calabria", "", "", "IT", "RE", "Reggio Emilia", "", "",
			"IT", "RG", "Ragusa", "", "", "IT", "RI", "Rieti", "", "", "IT",
			"RM", "Roma", "", "", "IT", "RN", "Rimini", "", "", "IT", "RO",
			"Rovigo", "", "", "IT", "Roma", "Roma", "", "", "IT", "SA",
			"Salerno", "", "", "IT", "SI", "Siena", "", "", "IT", "SO",
			"Sondrio", "", "", "IT", "SP", "La Spezia", "", "", "IT", "SR",
			"Siracusa", "", "", "IT", "SS", "Sassari", "", "", "IT", "SV",
			"Savona", "", "", "IT", "TA", "Taranto", "", "", "IT", "TE",
			"Teramo", "", "", "IT", "TN", "Trento", "", "", "IT", "TO",
			"Torino", "", "", "IT", "TP", "Trapani", "", "", "IT", "TR",
			"Terni", "", "", "IT", "TS", "Trieste", "", "", "IT", "TV",
			"Treviso", "", "", "IT", "UD", "Udine", "", "", "IT", "VA",
			"Varese", "", "", "IT", "VB", "Verbano Cusio Ossola", "", "", "IT",
			"VC", "Vercelli", "", "", "IT", "VE", "Venezia", "", "", "IT",
			"VF", "Vigili del Fuoco, Feuerwehr", "", "", "IT", "VI", "Vicenza",
			"", "", "IT", "VR", "Verona", "", "", "IT", "VT", "Viterbo", "",
			"", "IT", "VV", "Vibo Valentia", "", "", "IT", "ZA", "Zara", "", "" };

	private ArrayList<String> find(String Suche, String Land,
			boolean exect, int offset, boolean old) {
		ArrayList<String> list = new ArrayList<String>();
		// wenn lehrer suchbegriff
		if (Suche.length() == 0) {

			return list;
		}
if(Suche.compareTo("ALL")==0){
//	Suche="";
}
		// haptfunktion
		int difLength = Suche.length();
		String out = "";
		for (int i = 0; i < aSuch.length / 5; i++) {

			if ((aSuch[i * 5] == Land
					&& aSuch[i * 5 + 1 + offset].length() == difLength
					&& 0 == aSuch[i * 5 + 1 + offset].substring(0, difLength)
							.compareToIgnoreCase(Suche) && exect)
					&& (old || aSuch[i * 5 + 4].compareTo("X") != 0)
					|| aSuch[i * 5] == Land
					&& aSuch[i * 5 + 1 + offset].length() > difLength
					&& 0 == aSuch[i * 5 + 1 + offset].substring(0, difLength)
							.compareToIgnoreCase(Suche)
					&& exect == false
					&& (old || aSuch[i * 5 + 4].compareTo("X") != 0)) {
				// Log.i("KFZ",aSuch[i*5]+" "+aSuch[i*5+1]+" "+aSuch[i*5+2]);
				list.add(aSuch[i * 5]);
				list.add(aSuch[i * 5 + 1]);
				list.add(aSuch[i * 5 + 2]);
				list.add(aSuch[i * 5 + 3]);
				list.add(aSuch[i * 5 + 4]);

			} else {
				// out=aSuch[i*3]+" "+aSuch[i*3+1]+" "+aSuch[i*3+2]+"\n";
			}

		}
		out += "\n";

		return list;
	}
	ArrayList<String> findKFZ(String Suche, String Land,
			boolean exect, boolean old) {
		return find(Suche, Land, exect, 0, old);
	}
	 ArrayList<String> findRueck(String Suche, String Land,
			boolean exect, boolean old) {
		return find(Suche, Land, exect, 1, old);
	}
}
